### ISSUE TITLE
Interest in More Custom Clippy Docs/Website?

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rust-clippy#1088]
Clippy's docs (the wiki page) is getting longer and longer and could be improved quite a bit by adding a more custom search with a few filter options. <kbd>cmd</kbd>+<kbd>f</kbd> works okay, but only too a certain extend.

I think I could whip something up quite quickly by dumping the lint info not to a wiki string, but into a JSON file. The result would looks like [bitrust](http://killercup.github.io/bitrust/), but with lints instead of commits.

Would this be something you'd like to have? Do you have some other ideas for this?

**Comment by Manishearth** [comment]
👍

**Comment by mcarton** [comment]
Something like this should be able to automatically update when we push to master (even better: when we release a new version, Travis tests tags I believe).
Cc https://github.com/Manishearth/rust-clippy/issues/569.

----

Also I'm not a big fan of JavaScript heavy websites (but I guess it's my fault for not living with my time):

![screen shot 2016-07-12 at 13 28 27](https://cloud.githubusercontent.com/assets/3751788/16765614/54a2e81a-4835-11e6-93ed-05e8ee977603.png)

**Comment by killercup** [comment]
> Also I'm not a big fan of JavaScript heavy websites

Me too, as really often it's not necessary. Sadly, it's much easier to do that (take JSON, filter by fields, output HTML). I'm probably going to copy that page and just adjust the output a bit.

It's not set in stone, though, feel free to change it :)

**Comment by tillarnold** [comment]
I don't know how relevant this is to clippy but anyways: At work we use an older version of jshint. And while configuring jshint I had some problems because some things had different names in the old version or had some other subtle differences. But the jshint website only shows the documentation for the newest version. I probably could have tried to build an old version of the webpage locally but I just ended up looking at the code and figuring things out this way. I don't know if this would be difficult to do but it might be nice if you could see the documentation for the lints for all releases of clippy. (Like with a little dropdown where you can select the version)  But I don't think that that's really important. I't would just be nice to have.

**Comment by mcarton** [comment]
I try to maintain [a changelog](https://github.com/Manishearth/rust-clippy/blob/master/CHANGELOG.md) for Clippy with new lints, breaking changes in *rustc* API and other random things I fell should be in there. But I'm pretty sure I forgot to update it more than once.

**Comment by killercup** [comment]
Hm, versioning clippy is interesting. A use case: I may be stuck on a specific nightly that requires me to stay on an older clippy release.

There are a few things we could do to supply versioned docs:

- Only update the gh-pages branch when a new git tag is published (= new release) and use https://rawgit.com to link to older versions
- Keep versioned JSON files in the gh-pages branch and make them selectable (`lints.json` is currently 83kB uncompressed)
- Embed the docs into `cargo clippy`, e.g. `cargo clippy --help=lints`

**Comment by mcarton** [comment]
IMO the doc should be available at `whatever/v0.0.xy/index` with a redirection on `whatever/current/index` and all docs should stay there forever. I don't see the point of https://rawgit.com :confused:
(Bonus point if the old docs contain whatever tag search engines need to know where is the lastest version. Google tends to give a random old version of any page of Boost docs)

As for embedding the docs in `cargo clippy`, why not, but generating them requires python and Clippy’s sources. This could be done in a `build.rs`, but can `cargo install` currently install any data files?

**Comment by oli-obk** [comment]
Are there any more actions required to resolve this issue?

**Comment by killercup** [comment]
I don't think so. Just ping me if something comes up!
