### ISSUE TITLE
False positive on boxed_local for Box<Self> parameters

### ISSUE THREAD

**Issue by leodasvacas** [rust-lang-nursery/rust-clippy#1123]
Some traits such as [FnBox](https://doc.rust-lang.org/std/boxed/trait.FnBox.html) define methods that take `Box<Self>`. Implementing such a method will incorrectly trigger the `boxed_local` lint.

**Comment by llogiq** [comment]
See also #916

**Comment by 0ndorio** [comment]
I think I hit this old issue with the following playground example [1]. I know that `self: Box<Self>` as function parameter is a bit odd, but the trait implementation can't change much about the trait definition.

[1] https://play.rust-lang.org/?gist=5720b0cda84efeb89752c7491acd40ab&version=stable&mode=debug

**Comment by phansch** [comment]
Fixed via #3321 (feel free to re-open if it's still a problem)
