### ISSUE TITLE
Macro check for useless_format

### ISSUE THREAD

**Issue by llogiq** [rust-lang-nursery/rust-clippy#1130]
This lint also fires within macros that use `format!(..)` on their args. While possible to avoid, this comes at the cost at some duplicate code with little benefit.

The major complication here is that `format!(..)` itself is a macro, so we'd need to check if the `format!(..)` macro was called from another macro expansion.

**Comment by gnzlbg** [comment]
There is a mwe for this here: https://github.com/rust-lang-nursery/rust-clippy/issues/2424#issue-293607438
