### ISSUE TITLE
Spurious `absurd_extreme_comparisons` involving `usize`

### ISSUE THREAD

**Issue by scurest** [rust-lang-nursery/rust-clippy#1159]
```
fn too_big_for_memory(len: u64) -> bool {
    len >= std::usize::MAX as u64
}
```

spuriously triggers `absurd_extreme_comparisons` with a 64-bit target (I assume it doesn't for other bitsizes, but I don't have an easy way to check). I'd be nice for `std::usize::MAX` to not evaluate to a constant in this case.

**Comment by oli-obk** [comment]
we should probably treat any cast from a target-sized type to a fixed size type as unanalyzable by the `absurd_extreme_comparisons` lint.

**Comment by kimsnj** [comment]
I'll try to shortly make a PR for this issue (as a first time contribution to clippy :) )

**Comment by oli-obk** [comment]
🎉 awesome!

If you have any questions, feel free to ping me on irc.mozilla.org in #clippy or just ask here
