### ISSUE TITLE
cargo clippy yields "error while loading shared libraries"

### ISSUE THREAD

**Issue by xetra11** [rust-lang-nursery/rust-clippy#1238]
`/home/xetra11/.cargo/bin/cargo-clippy: error while loading shared libraries: librustc_driver-8102e29f.so: cannot open shared object file: No such file or directory
`

After updating rustup, nightly and cargo installing clippy I'm still unable to run clippy by `cargo clippy`. I found many similar issues but adding `/usr/local/lib` to the `ld.so.conf` file did not helped.

I'm running Linux Mint fyi.

**Comment by mcarton** [comment]
See https://github.com/Manishearth/rust-clippy/issues/964#issuecomment-249031082.

**Comment by jbolila** [comment]
```bash
export LD_LIBRARY_PATH=$HOME/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/
```

works.
