### ISSUE TITLE
Forbid: Unconditional Self-Recursive Function Calls

### ISSUE THREAD

**Issue by nordlow** [rust-lang-nursery/rust-clippy#1379]
It would be very nice to have a plugin that forbids functions from calling themselves with the exact same unchanged arguments as it was called with in (pure) functions that doesn't change any (global) state that affects the control flow of the current function. Such a bug often exhausts the stack resulting in a hard-to-debug memory fault.

I've done this mistake several times in most languages I've worked with.

I call this: unconditional self-recursion.

**Comment by oli-obk** [comment]
we probably need to analyze the optimized MIR to prove this in many cases (there will still be false negatives)

**Comment by clarcharr** [comment]
Isn't this already a lint on upstream? `unconditional_recursion` warns when the same function is called recursively and not wrapped in a conditional branch.

**Comment by sanmai-NL** [comment]
@nordlow: can this issue be closed based on @clarcharr’s observation?

**Comment by nordlow** [comment]
Yes, looks fine. Thanks!
