### ISSUE TITLE
Add lint for usage of #[inline]

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rust-clippy#1503]
I'd like a configurable lint for detecting the usage of `#[inline]` or lack thereof, with the following two options:

- enforce usage of `#[inline]`, enforce lack of `#[inline]`.
- on public "items" (functions/methods/associated functions), on private "items", "everywhere".

This lint should be disabled by default, but some crates that define a lot of one liner functions will find it useful to enforce that all their functions are inline. Otherwise, these functions won't be inlined in crates downstream.

**Comment by shssoichiro** [comment]
I personally don't see the use case for wanting a lint that enforces or refuses `#[inline]` for *every* function. What might be more useful is some sort of metric to calculate how useful adding or removing `#[inline]` might be for each function, and generating suggestions based off of that.

**Comment by gnzlbg** [comment]
Maybe we could add it as a third option here, to use an euristic, but I have some crates already where the exceptional thing to do is to not mark a function as inline. I would really like to have a lint that helps me do that.

**Comment by mcarton** [comment]
Any heuristic we could write in Clippy to guess if a function should be inlined would be surpassed by LLVM anyway.

**Comment by gnzlbg** [comment]
The heuristic could tell you "maybe you want to put `#[inline]`" on that function. Without that LLVM cannot consider it for inlining at all.

**Comment by mcarton** [comment]
Yes it can:

```rust
#![feature(test)]

extern crate test;

fn foo() -> u32 {
    42
}

fn main() {
    let a = foo();
    test::black_box(a);
}
```

With:
```
rustc --emit=llvm-ir -O a.rs
```

This generates:
```llvm
define internal void @_ZN1a4main17he35c060357534f1aE() unnamed_addr #0 {
entry-block:
  %dummy.i = alloca i32, align 4
  %0 = bitcast i32* %dummy.i to i8*
  call void @llvm.lifetime.start(i64 4, i8* %0) #2
  store i32 42, i32* %dummy.i, align 4
  call void asm "", "r,~{dirflag},~{fpsr},~{flags}"(i32* nonnull %dummy.i) #2, !srcloc !1
  call void @llvm.lifetime.end(i64 4, i8* %0) #2
  ret void
}
```

`foo` has been inlined even without `#[inline]`.

**Comment by shssoichiro** [comment]
My understanding is that `#[inline]` allows functions to be inlined *across crates*, and all functions can by default be inlined within the same crate.

**Comment by Manishearth** [comment]
Yes, that is the case. `#[inline]` is not an annotation LLVM can help with.

**Comment by clarcharr** [comment]
I mean, you could check a small case for small expressions that could be marked as inline. But I'm not sure how useful such a lint would be.

**Comment by gnzlbg** [comment]
@mcarton we were only talking about inlining across crates here, hence the emphasis on _public items_. It just turns out that marking public items inline is not enough for proper cross-crate inlining.

**Comment by gnzlbg** [comment]
So basically I needed this again. Would you accept a PR with a lint that warns if a function in a crate isn't `#[inline]` ?

There are some crates where I want each function to actually be `#[inline]` (so that it can be inlined across translation units without LTO, which at least for my crates is required for correctness). I'd like to activate such a lint in those crates and explicitly opt out of those functions that do not need to be inline.

**Comment by oli-obk** [comment]
> is required for correctness

How does the "can be inlined" ability affect correctness?

It feels like a restriction lint ("require all functions to be `#[inline]`"), but I don't think we have precedent for similar lints.

Won't you be served better by `-Zalways-emit-mir`? That won't cause any inlining, but the ability to inline would be there.

**Comment by gnzlbg** [comment]
> How does the "can be inlined" ability affect correctness?

When target features are involved a function not being inlined causes all sorts of issues: https://github.com/rust-lang-nursery/stdsimd/issues?utf8=%E2%9C%93&q=is%3Aissue+inline

> It feels like a restriction lint ("require all functions to be #[inline]"), but I don't think we have precedent for similar lints.

To me this just sounds like the missing docs lint (with missing `#[inline]` instead which is suspiciously similar to missing `#[doc]`).

**Comment by oli-obk** [comment]
> To me this just sounds like the missing docs lint but with missing #[inline] instead which is suspiciously similar to missing #[doc].

Yay precedent

> If the intent for a function is to always be inlined, when it isn't, then that's a bug

Isn't that `#[inline(always)]`?

Is this lint going to be useful for anybody besides stdsimd?

**Comment by gnzlbg** [comment]
> Isn't that #[inline(always)]?

No. `#[inline(always)]` requires a function to _always_ be inlined into the caller. If this is not possible, that produces a compilation error, which prevents the caller from using a function. `#[inline]` allows the function to be inlined, but if it cannot be inlined into the caller, then that's fine too.

> Is this lint going to be useful for anybody besides stdsimd?

If you have a public method that's not inline and LTO is disabled, it **cannot** be inlined into dependent crates. So if you have a crate where you want most of your methods to be inlined into callers when that's profitable even if LTO is disabled, the language feature that you need to use is `#[inline]`. 

An example of where this happens often is in crates implementing collections. For example, check [`SmallVec/lib.rs`](https://github.com/servo/rust-smallvec/blob/master/lib.rs) which marks most of its public methods inline. Most of the methods are tiny, but without `#[inline]` cannot be inlined into the caller. For such a library, having a lint that allows them to explicitly opt-out some methods from being inline is useful.

**Comment by oli-obk** [comment]
> > If the intent for a function is to always be inlined, when it isn't, then that's a bug
> #[inline(always)] requires a function to always be inlined into the caller. If this is not possible, that produces a compilation error. This prevents the caller from using that function from that context. #[inline], on the other hand, allows the function to be inlined, but if it cannot be inlined into the caller, then that's fine too.

Now I'm confused. It's "fine if it cannot be inlined into the caller", but it's "a bug to not inline the function"? XD

**Comment by gnzlbg** [comment]
> Now I'm confused. It's "fine if it cannot be inlined into the caller", but it's "a bug to not inline the function"? XD

Yeah, that pretty much sums it up. When the function can be inlined, it is a bug not to inline it. But when a function cannot be inlined, then it is a bug to inline it.
