### ISSUE TITLE
Suggest using function instead of method syntax when cloning a ref-counted pointer.

### ISSUE THREAD

**Issue by nical** [rust-lang-nursery/rust-clippy#1645]
It would be useful to have a lint that suggests using the function syntax ```let data = Arc::clone(&image.data);``` over the method syntax ```let data = image.data.clone();``` when cloning a standard reference counted pointer (```std::rc::Rc```, ```std::sync::Arc```, ```std::rc::Weak``` and ```std::sync::Weak```).

The motivation behind this is explained in the [rust lang RFC pull request #1954](https://github.com/rust-lang/rfcs/pull/1954). In a nutshell, ```Clone``` is a very vaguely defined concept. Implementations can be shallow or deep clones which, as the [standard library documentation](https://doc.rust-lang.org/std/clone/trait.Clone.html) puts it "may or may not be expensive". Clone being the only way to add a reference to a reference counted object, it can sometimes be hard to see whether some code is trivially cheap or if it is prohibitively expensive without looking up the exact type. The RFC contains a [concrete example](https://github.com/nical/rfcs/blob/rc-newref-clone/text/0000-rc-newref-clone.md#example).

Using the function syntax ```let data = Arc::clone(&image.data);``` makes it clear that an Arc is being cloned and not the entire image.

**Comment by oli-obk** [comment]
We already have lints for cloning references. The code there could be extended with this lint, since most of the framework already exists.

The lint should probably have a suggestion, too.

**Comment by Aaron1011** [comment]
I'd like to work on this.

**Comment by oli-obk** [comment]
It's all yours

**Comment by Aaron1011** [comment]
@oli-obk: I believe that this can be closed now.

**Comment by oli-obk** [comment]
Ah right. In the future, you can write "closes #1645" in the PR, in order to have github close it automatically when the PR is merged

**Comment by Aaron1011** [comment]
@oli-obk: I did (see the reference above my comment), but it wasn't closed automatically. I think it only works for people with commit access.

**Comment by oli-obk** [comment]
I don't think it can process the word "issue". Github's patterns are pretty simplistic ;)
