### ISSUE TITLE
New Lint: Pass small trivially copyable objects by value

### ISSUE THREAD

**Issue by Evrey** [rust-lang-nursery/rust-clippy#1680]
Based on [this HIC++ guideline](http://www.codingstandard.com/rule/8-2-3-pass-small-objects-with-a-trivial-copy-constructor-by-value/). For any instance object of type `T` that implements `Copy` and for which `mem::size_of::<T>() <= (2 * mem::size_of::<usize>())`, clippy should warn about using `&T` parameters in function and suggest passing the instance objects by value instead.

The reasoning behind this is that in many calling conventions instances of structs will be passed through registers if they fit into two or less general purpose registers. For x86_64 this means that a struct instance of up to 16 bytes in size will be passed through registers instead of a pointer to the stack. Besides: In this case a pointer would be anywhere from 50% to 800% the size of the actual struct instance.

**Comment by Evrey** [comment]
Things to consider:

- What if a project is compiled to both, x86_64 and x86 targets? Use `u64` as reference size instead of `usize`? For exotic platforms like 16-bit architectures, one could allow the user to configure the "pass by value size", e.g. `#![clippy(pass_by_value_size = "16")] // bytes`.
- Propably ignore `trait` or generic functions and let compiler optimisation handle this.

**Comment by sanmai-NL** [comment]
As for your first consideration, my suggestion is to emit different warnings based on the current target during compilation. The programmer is then to choose the solution, e.g. setting `pass_by_value_max_size` or ignoring the warning.
