### ISSUE TITLE
Suggest to insert underscores into long numeric literals

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#1736]
I don't even know what `61864918973511` is, but `61_864_918_973_511` I can quickly count to be 61 Trillion (In case I got the US naming scheme right. In germany it would be a Billion).

**Comment by clarcharr** [comment]
One note: I think that defaulting to thousands separations is good but I think it'd be good to also suggest ten-thousands separation or other separation, because other languages don't follow the SI/PIE system of separating by thousands.

For example, a million in Chinese is actually a hundred ten-thousands.

**Comment by jayhardee9** [comment]
Hi, can I pick this one up?

**Comment by Manishearth** [comment]
Sure!

Let me know if you have any questions

**Comment by jayhardee9** [comment]
Thanks! These are the cases that I think should trigger the lint:
* hex literals with more than 4 digits that are neither grouped into bytes nor words by underscores,
* decimal literals with more than 3 digits that are not grouped into thousands,
* same rule for octal literals as decimal literals (I'm not so sure about this one),
* binary literals with more than 8 digits that are neither grouped into nibbles nor bytes.
For hex and binary literals that have two common groupings (I think the lint should accept/recommend both styles), the grouping should be consistent (no `0xDEAD_BE_EF`, for example). 

Thoughts?

**Comment by Manishearth** [comment]
This sounds good to me.

**Comment by clarcharr** [comment]
@jayhardee9 I would modify the decimal separator rule to say that literals more than five digits should be grouped in groups of no larger than 4 digits; this allows for non-European groupings which is congruent with other languages. See: https://en.wikipedia.org/wiki/Decimal_mark#Digit_grouping

If the literal doesn't match this rule, I think that grouping into thousands as a suggestion is fine.

I do think that octal literals I think that 3 is a solid standard.

**Comment by killercup** [comment]
Interesting lint. I think this is something that might also be in rustfmt's domain.

Pro "always group by 3": SI prefixes.

Con "always group by three": `let cents = 24_95;`

**Comment by oli-obk** [comment]
> Con "always group by three": let cents = 24_95;

Yea, I think if someone is doing a certain "reasonable" grouping we shouldn't interfere. So even `0b000_100_101` sounds fine by be. Inconsistent, missing or too large grouping is the only problematic pattern I see.

@clarcharr 's rule could be extended to all literals. Just define a maximum, not a specific target grouping.

**Comment by jayhardee9** [comment]
So digit grouping should be independent of the radix? If so, then it remains to set a maximum grouping. Four digits seems reasonable to me.

**Comment by Manishearth** [comment]
Fixed in #1900
