### ISSUE TITLE
Lint `'static` lifetimes in the type of statics/consts

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#1762]
see https://github.com/rust-lang/rust/pull/41957#discussion_r116365381 for an example

RFC 1623 allows writing `const FOO: &str = "bar"` instead of `const FOO: &'static str = "bar"`

**Comment by gbip** [comment]
I might want to implement this lint as a first contribution, but first I have to make sure I have the time to do so.
I will keep you updated !

**Comment by mcarton** [comment]
@gbip Great! Don't hesitate to ask if you have any question.

**Comment by gbip** [comment]
Here is the implementation : #1829 !

**Comment by oli-obk** [comment]
This has been implemented in #2151
