### ISSUE TITLE
Panic during linting involving complicated `match` statements

### ISSUE THREAD

**Issue by Ameobea** [rust-lang-nursery/rust-clippy#1782]
I've encountered an error when linting my project resulting in a panic while compiling.  

* **Compiler Version**: rustc 1.19.0-nightly (5f3966864 2017-05-25)
* **Failing Code**: 
```rust
match Some(()) {
    Some(_) => unsafe { ptr::write(ptr::null_mut() as *mut u32, mem::transmute::<[u8; 4], _>([0, 0, 0, 255])) },
    None => unsafe { ptr::write(ptr::null_mut() as *mut u32, mem::transmute::<[u8; 4], _>([13, 246, 24, 255])) },
}
```
* **Backtrace**: https://gist.github.com/Ameobea/d57a03bf41993522bddf16afd8b69017

I've created a [PR](#1783) that includes a new test that causes a panic.  I was unable to determine the cause of the panic myself or go about fixing it, however.

**Comment by oli-obk** [comment]
It's the copy paste Lint's fault. We probably messed up something around body tables again
