### ISSUE TITLE
Rust API Guideline: Cargo.toml publishes CI badges for tier 1 platforms

### ISSUE THREAD

**Issue by mcarton** [rust-lang-nursery/rust-clippy#1792]
As per [Cargo.toml publishes CI badges for tier 1 platforms](https://github.com/brson/rust-api-guidelines#cargotoml-publishes-ci-badges-for-tier-1-platforms-c-ci).

**Comment by clarcharr** [comment]
I think that this one should be allow-by-default because not every crate wants to put an explicit dependency on GitHub/Travis/AppVeyor.

**Comment by mcarton** [comment]
GitLab is also possible, but I agree that the set of supported CI is rather small for now.

**Comment by phansch** [comment]
Yup, going ahead and closing this. I created https://github.com/rust-lang-nursery/rust-clippy/issues/2674 to check for a CI setup instead.
