### ISSUE TITLE
Example tests should be using diff, not git diff

### ISSUE THREAD

**Issue by Manishearth** [rust-lang-nursery/rust-clippy#1811]
The example tests [overwrite the existing output file and then run git diff](https://github.com/Manishearth/rust-clippy/blob/master/tests/examples.rs#L38)

I don't think that's a good idea; tests shouldn't touch the working dir. Would be preferable to make a new file in a tempdir and do `diff -U8` or `diff -u8` on linux. Env var to recover the overwriting behavior would be fine.

cc @oli-obk

**Comment by eddyb** [comment]
Why not use `compiletest` in UI test mode?

**Comment by oli-obk** [comment]
Because we needed to abuse compiletest to get it working with the plugin, because it doesn't cope well with Travis caches, because you can't just rerun that one failing test.... using crate examples is much cleaner imo because we don't need to reinvent cargo to run some tests.

I chose the overwriting behaviour, because the files are checked into git, so nothing can be lost by overwriting them, and in every single usage off ui tests, I always ran the update script. I don't see any reason to fail the test and not update the files.

The env var solution is fine with me though.

**Comment by Manishearth** [comment]
> I don't see any reason to fail the test and not update the files.

If you're still experimenting locally and want to see the differences in the output.

This basically assumes that local test updates have been checked in to git (or at least added to the index). I don't think that's a reasonable expectation, and it's _very_ surprising for a build process to change non-ignored files in the worktree.

**Comment by eddyb** [comment]
Those all sound like things that should be fixed in `compiletest` IMO. There's no reason you'd have to hack up your own UI tests. Also, the idea of an update script is dangerous IMO - I double-check *every single difference* by hand to make sure it's intentional.

**Comment by llogiq** [comment]
Isn't there some kind of diff lib that e.g. `rustfmt` uses? We could diff within Rust...

**Comment by eddyb** [comment]
@llogiq There is already a tool for doing all of this and it's compiletest UI tests.

**Comment by oli-obk** [comment]
I also check every change, but I check them before committing. Maybe compiletest should be taken out of tree? So it can be developed independently and rustc only updates it as a crates dependency?

**Comment by eddyb** [comment]
cc @nikomatsakis (about compiletest)

**Comment by mcarton** [comment]
> Maybe compiletest should be taken out of tree?

[It already kind of is but not really](https://crates.io/crates/compiletest_rs). That's is what we use, it's mostly a copy of the one from rustc's repo (but having updated it once or twice I know it's not an exact copy).

**Comment by oli-obk** [comment]
I just checked the unstable features used by compiletest. It could be made completely stable. This way rustc doesn't have to worry about rustc changes breaking an external project needed by rustc.

**Comment by nikomatsakis** [comment]
> I also check every change, but I check them before committing. Maybe compiletest should be taken out of tree? So it can be developed independently and rustc only updates it as a crates dependency?

I am in favor of this. It seems ludicrous for compiletest to rely on unstable code.

**Comment by oli-obk** [comment]
We're not using git diff anymore.
