### ISSUE TITLE
Lint to suggest starts_with and ends_with instead of chars().next().unwrap()

### ISSUE THREAD

**Issue by clarcharr** [rust-lang-nursery/rust-clippy#1818]
Substitutions:

`s.chars().next().unwrap() == 'c'` => `s.starts_with('c')`
`s.chars().next_back().unwrap() == 'c'` => `s.ends_with('c')`
`s.chars().last().unwrap() == 'c'` => `s.ends_with('c')`

**Comment by llogiq** [comment]
Note that the former will also panic on empty strings.

**Comment by mcarton** [comment]
@llogiq on the other hand we already have all the [logic for method chains](https://github.com/Manishearth/rust-clippy/blob/07c25ea4394f5d0ec2d233c04609c98859fd8a58/clippy_lints/src/methods.rs#L561) implemented properly with `hir` so doing it with `ast` would probably need more work :smile:

Still easy though.
