### ISSUE TITLE
needless_pass_by_value on annotation?

### ISSUE THREAD

**Issue by Dandandan** [rust-lang-nursery/rust-clippy#1876]
I use Rocket with Rust nightly. Clippy gives me this suggestion (that doesn't compile of course).

warning: this argument is passed by value, but not consumed in the function body
  --> src/main.rs:23:1
   |
23 | #[get("/")]
   | ^^^^^^^^^^^ help: consider taking a reference instead `&#[get("/")]`
   |
   = note: #[warn(needless_pass_by_value)] on by default
   = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_pass_by_value

**Comment by C-Bouthoorn** [comment]
I just got the same warning. `&#[get("/")]` is not valid though. I'm also using Rocket, but it seems to come from Hyper.
