### ISSUE TITLE
Move into nursery

### ISSUE THREAD

**Issue by Manishearth** [rust-lang-nursery/rust-clippy#1889]
Any objections @llogiq @birkenfeld @mcarton @oli-obk @killercup ?

**Comment by oli-obk** [comment]
Quite the contrary. Let's do this!

**Comment by mcarton** [comment]
:tada:

**Comment by llogiq** [comment]
After moving, does the old repo address redirect? There are a lot of links to the current repo.

Regardless, I vote yay! Let's get clippy into nursery!

**Comment by llogiq** [comment]
https://m.youtube.com/watch?v=hdcTmpvDO0I

**Comment by killercup** [comment]
Yeah, Github will automatically redirect from old repo URLs to new ones.

llogiq <notifications@github.com> schrieb am Sa. 15. Juli 2017 um 07:53:

**Comment by Manishearth** [comment]
Just need admin on rust-lang-nursery to push this cc @nrc

**Comment by Manishearth** [comment]
Done.

**Comment by Manishearth** [comment]
Lmk if those of you with access still have it. You should.

**Comment by killercup** [comment]
@Manishearth I think you can also drop the "rust" from the name now… "rust-lang-nursery/rust-clippy" has a bit of a stutter to it.

**Comment by llogiq** [comment]
@killercup should we rename the `rustdoc`repo to `doc` then, too?

**Comment by killercup** [comment]
@llogiq no, rename the `clippy` binary to `rust-clippy` of course :trollface:
