### ISSUE TITLE
Lint request: warn mutable range bound variable

### ISSUE THREAD

**Issue by HongxuChen** [rust-lang-nursery/rust-clippy#1901]
Rust uses `..` as the syntactic sugar for range construct however it might be misused as a replacement for *for-loop* in C/C++: the range bounds (`start`/`end`) are captured at the site of the range initialization and remain unchanged, therefore modifying them inside range loop doesn't reflect the range iterations.

```rust
fn main() {
  let mut m = 4;
  for i in 0..m {
    if i == 2 {
      m = 2;
    }
    println!("i={}, m={}", i, m);
  }
}
```

The suggested detection pattern: there is a mutable binding that is used as a range bound, and the variable may be possibly updated in the range loop.

**Comment by lpesk** [comment]
I'll work on this! (New contributor so will probably be back with questions.)

**Comment by llogiq** [comment]
Great! Feel free to ask any question you may have (either here, on /r/rust or IRC or wherever you find one of us).
