### ISSUE TITLE
Please push v0.0.145 tag

### ISSUE THREAD

**Issue by Keruspe** [rust-lang-nursery/rust-clippy#1905]
It would be great if all releases got a tag here, it would really improve the packaging for distributions.

**Comment by oli-obk** [comment]
Sorry forgot about it. Wait... clippy gets packaged? I didn't know that, cool.

**Comment by Keruspe** [comment]
At least on Exherbo it's packaged by me :)

**Comment by oli-obk** [comment]
How are you keeping it in sync with nightly?

**Comment by oli-obk** [comment]
I pushed a new tag.
