### ISSUE TITLE
Lint excessive `use` statements

### ISSUE THREAD

**Issue by FaultyRAM** [rust-lang-nursery/rust-clippy#1911]
Code that imports items from the same namespace via multiple `use` statements, such as:

```rust
use foo;
use foo::Bar;
```

can be refactored into a single line like so:

```rust
use foo::{self, Bar};
```

**Comment by killercup** [comment]
cc https://github.com/rust-lang-nursery/fmt-rfcs/issues/24

**Comment by oli-obk** [comment]
I think this should be completely solved by rustfmt. @FaultyRAM if you agree, please close, otherwise please comment why you think clippy should address this, too, or could address it better.
