### ISSUE TITLE
Clippy told me to write an invalid line

### ISSUE THREAD

**Issue by ProgramFOX** [rust-lang-nursery/rust-clippy#1918]
I have this Rust function (the `get` attribute and `Template` come from the web framework Rocket):
```
#[get("/")]
fn index() -> Template {
    Template::render("home/index", empty_hashmap())
}
```
When running Clippy over my code, it said something about this function:

```
 --> src\controllers\home.rs:4:1
  |
4 | #[get("/")]
  | ^^^^^^^^^^^ help: consider taking a reference instead: `&#[get("/")]`
  |
  = note: #[warn(needless_pass_by_value)] on by default
  = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#needless_pass_by_value
```
Alright, so I did what Clippy told me:

```
&#[get("/")]
fn index() -> Template {
    Template::render("home/index", empty_hashmap())
}
```
However, the compiler wasn't too happy with that:
```
error: expected item, found `&`
 --> src\controllers\home.rs:4:1
  |
4 | &#[get("/")]
  | ^
```

Is it a bug in Clippy that it suggests me to write this line? Or is it a problem from Rocket, or just my misunderstanding?

**Comment by oli-obk** [comment]
This is actually a rustc bug: https://github.com/rust-lang/rust/issues/43268

We have an issue open in this repo at #1885, so I'll close this issue in favour of the other one.
