### ISSUE TITLE
Suggestion: Not (`!`) `is_some`, `is_none`, `is_ok`, `is_err` lints

### ISSUE THREAD

**Issue by expenses** [rust-lang-nursery/rust-clippy#1930]
Using `Option::is_none` should always be preferred to using `! Option::is_some` and vice-versa, and the same goes for `Result::is_ok` and `Result::is_err`. For example:

    let optional_string = Some("Hello world!");
    println!("{}", !optional_string.is_some());

Would be better written as 

    let optional_string = Some("Hello world!");
    println!("{}", optional_string.is_none());

**Comment by oli-obk** [comment]
This should be part of the lint that simplifies `!(foo == bar)` to `foo != bar`

**Comment by mikerite** [comment]
The `!Option::is_some` => `Option::is_none` style lints don't seem to be working. It looks like they were removed by bdf3887d22a7352c20d97cef9cf9f8f4ac41ccff. Was this intentional, @oli-obk?

**Comment by oli-obk** [comment]
That commit was part of a PR that moved stuff around. They were working after that PR. Maybe this is something in a recent nightly?

**Comment by mikerite** [comment]
Ok, it _is_ working. It's just that nonminimal_bool is Allow. Sorry.
