### ISSUE TITLE
verbose_bit_mask

### ISSUE THREAD

**Issue by HongxuChen** [rust-lang-nursery/rust-clippy#1940]
Correct me if I'm wrong, but for `x = 0b10000u16`, `x.trailing_zeros() > 4` and `x & 0b1111 == 0` are not equivalent. Shouldn't the advice be `>=`?

**Comment by mati865** [comment]
@HongxuChen do you want to fix it yourself?

**Comment by HongxuChen** [comment]
@mati865 seems you've made it, and thanks!

**Comment by mati865** [comment]
@HongxuChen I'm just playing around (it's another way to learn language).
You can open PR with fix if you want to be mentioned as contributor.

**Comment by HongxuChen** [comment]
@mati865 it's okay you open PR with your fix 😄
