### ISSUE TITLE
Suggest `x > y` over `x >= y + 1` for integers

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#1955]
Also all other combinations around comparison, and adding/subtracting 1 on either side.

**Comment by clarcharr** [comment]
This should also apply to changing `a..b + 1` to `a...b`.

**Comment by oli-obk** [comment]
That's still unstable, but once it becomes stable, yes, that should be linted against

**Comment by Nokel81** [comment]
Now that it has been stabilized shall I have a go at implementing the second part of the lint?

**Comment by oli-obk** [comment]
jup!

**Comment by Nokel81** [comment]
yup?

**Comment by oli-obk** [comment]
The second part is all yours

**Comment by jens1o** [comment]
shouldn't this be closed?

**Comment by oli-obk** [comment]
It doesn't seem to be working?

https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=758f95d32c643687e83127c749efe9b4

**Comment by jens1o** [comment]
oh okay. Thought that you have tests for that in the pr.

**Comment by oli-obk** [comment]
Oh yea, we do have tests. I just screwed up on the playground. [This](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=bdc49af7976fc1bfe6dc4e69a3095fbd) works.
