### ISSUE TITLE
int_ty_to_nbits is horrible

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#1957]
https://github.com/rust-lang-nursery/rust-clippy/blob/0e4c49b145a686c83fb669dabb39b9d13a9c6a97/clippy_lints/src/types.rs#L481-L493

If I'm reading this correctly,

1. we cast a rustc internal enum to a usize and hope that the indices don't change (which is probably already wrong since the introduction of `u128`).
2. we use the host pointer size instead of the target pointer size

Solutions for each

1. destructure the enum to obtain the correct values
2. use `tcx.data_layout.pointer_size.bits()`

**Comment by MaloJaffre** [comment]
I'll try to open a PR shortly to fix this.
