### ISSUE TITLE
Rename `match_path_old` to `match_path` after renaming the current `match_path` to `match_qpath`.

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#1983]
The naming is really unfortunate, especially since it sounds like we should be removing all `match_path_old` calls, which isn't possible.

**Comment by alexeyzab** [comment]
Hi there! I'd like to do this one.

**Comment by oli-obk** [comment]
Great! It's all yours

**Comment by mcarton** [comment]
Closed by #1987.
