### ISSUE TITLE
Parsable gcc-like output

### ISSUE THREAD

**Issue by CermakM** [rust-lang-nursery/rust-clippy#1985]
Hi, 
would it be possible ( if it is by now, how? ) to adjust the output so that it could be parsed in a gcc-like way, for example by using such features as csgrep? The goal here is to catch the defects by an event or a key. 

Thanks

**Comment by killercup** [comment]
The output is defined by rustc. There's currently a 'human' format (default text with colors), and JSON. You can get JSON by passing `--message-format json` to cargo build/check/clippy.

**Comment by CermakM** [comment]
Okay, thanks for the answer and for mentioning the JSON.

**Comment by oli-obk** [comment]
We can't do much here to change this, and I think the JSON is sufficient.
