### ISSUE TITLE
Better install instructions for stable

### ISSUE THREAD

**Issue by spease** [rust-lang-nursery/rust-clippy#2012]
Some explicit install instructions for stable rust would be nice. These seem to be the crucial two, although it looks like clippy is broken on nightly right this instant. 
```
rustup install nightly
rustup run nightly cargo install clippy
```

**Comment by spease** [comment]
Note that the second command can be simplified to
`cargo +nightly install clippy`
Although since clippy got fixed, I've been having trouble running it with just `cargo clippy`. So `cargo +nightly clippy` can be used to run it too.

**Comment by pravic** [comment]
Could not install clippy: tons of errors like

> error[E0609]: no field `int_type` on type `rustc::session::config::Config`

Version:

> $ rustc +nightly -vV
rustc 1.22.0-nightly (dd08c3070 2017-09-12)
binary: rustc
commit-hash: dd08c30703d052205a68ae34331eea464178cd99
commit-date: 2017-09-12
host: i686-pc-windows-msvc
release: 1.22.0-nightly
LLVM version: 4.0

> $ cargo show clippy
...
max_version: 0.0.159

Tried also 158, 157...

**Comment by oli-obk** [comment]
That's an independent issue #2047
