### ISSUE TITLE
Lint the creation of invalid references

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2028]
```rust
    let fake: &T = std::mem::zeroed();
```

Could be something a C/C++ developer considers correct if they don't know about Rust's (arguably unspecified) memory model (https://stackoverflow.com/questions/46084797/why-is-pointer-arithmetic-the-cause-of-a-segfault).

I think the only way references should be created in unsafe code is from dereferencing raw pointers.

We should probably lint calls to `std::mem::zeroed()` or `std::mem::uninitialized()`, the core variants or the `uninitialized` or `init` intrinsics.

**Comment by Manishearth** [comment]
This is easy to UB in C++ as well, though.

**Comment by oli-obk** [comment]
Depends on your usage. As long as you don't deref the pointer you're fine. Anyway, C++ should lint it, too ^^

**Comment by lpesk** [comment]
I'll work on this.

**Comment by oli-obk** [comment]
Great! Have a look at the various lints triggering on specific std lib functions and intrinsics. You can probably just check all function call expressions to the mentioned functions and check whether the expression's type is a reference
