### ISSUE TITLE
Help links are malformed

### ISSUE THREAD

**Issue by tridius** [rust-lang-nursery/rust-clippy#2033]
Using Clippy 0.0.157, the format of help links is as follows:
help: for further information visit [https://rust-lang-nursery.github.io/rust-clippy/0.0.157/index.html#temporary_cstring_as_ptr](https://rust-lang-nursery.github.io/rust-clippy/0.0.157/index.html#temporary_cstring_as_ptr)

Note the missing `v` before 0.0.157. All links that I have found are broken in this fashion, and require the version segment of the url to be /v[version.number.here]/ rather than /[version.number.here]/

So a correct link would look like this:
help: for further information visit [https://rust-lang-nursery.github.io/rust-clippy/v0.0.157/index.html#temporary_cstring_as_ptr](https://rust-lang-nursery.github.io/rust-clippy/v0.0.157/index.html#temporary_cstring_as_ptr)

**Comment by oli-obk** [comment]
Yea I screwed those up, but they have been fixed in the meantime in #2020 and will be in the next release

**Comment by tridius** [comment]
Ah didn't check closed issues. Thanks!

**Comment by mcarton** [comment]
At least we know people actually use those links and read our docs :smile:
