### ISSUE TITLE
Checks for Eq, PartialEq, Ord, and PartialOrd

### ISSUE THREAD

**Issue by Nokel81** [rust-lang-nursery/rust-clippy#2075]
This lint would word sort of like assert statements but be able checked at compile time. They would be warnings by default and check for things like:

1. `a < b` <==> `b >= a`
2. `a <= b` <==> `b > a`
3. `a == b` <==> `b == a`
4. `a != b` <==> `b != a`

**Comment by gnzlbg** [comment]
@oli-obk triage? I am not sure what @Nokel81 meant. How would the lint check for this at compile-time ?

**Comment by oli-obk** [comment]
I'm also not sure. We can't check for commutativeness at compile time without running into halting problem issues. We could probably run some sort of symbolic execution on the functions and check if we get the same result?

Or we can check that one forwards to the other and complain otherwise. But I'm not sure if that is possible in all cases.

**Comment by Nokel81** [comment]
What I was thinking was the second. Symbolic execution.

**Comment by gnzlbg** [comment]
How would that work? 

Rust code inside these impls could do arbitrary things, including calling opaque functions via C FFI.

**Comment by Nokel81** [comment]
By doing a restriction on what sort of code should be called in such a function body. Of course you could turn it off if you know for certain that they black box is correct

**Comment by gnzlbg** [comment]
So what code would be allowed? Is unsafe code ok? Is non-const code ok?

**Comment by oli-obk** [comment]
Yea this is fairly involved and will essentially be a part of any symbolic execution scheme when we get one. Seems like we should rather be discussing symbolic execution support for miri.

I don't think this is actionable with reasonable effort for the forseeable future

**Comment by gnzlbg** [comment]
@oli-obk is there a discussion about that somewhere?

**Comment by oli-obk** [comment]
Nope, feel free to open one. But note that I'm not gonna work on it in the next 6 months.
