### ISSUE TITLE
verbose_bit_mask: the suggested alteration is not good

### ISSUE THREAD

**Issue by malbarbo** [rust-lang-nursery/rust-clippy#2078]
When the operand is 1, the suggestion is more verbose than the original code:

Original code: `self.0 & 1 == 0` 
Suggested code: `self.0.trailing_zeros() >= 1`

**Comment by llogiq** [comment]
Agreed, the lint should habe a (for bonus points: configurable) lower bound of trailing zeroes. I think below 5, the lint makes little sense.

**Comment by ykrivopalov** [comment]
Hi! I want to fix this issue, but I failed to build clippy from master (c3df3bc).
I have rustc 1.22.0-nightly (14039a42a 2017-09-22).
https://gist.github.com/ykrivopalov/05ee6d52ab69a8b707e89450c4e810cd

Is it because rustc too fresh?)

**Comment by mrbuzz** [comment]
Hi! I was looking for a "good first issue" and I came across this one. Shouldn't this be marked as closed? As I can see a solution has already been merged

**Comment by phansch** [comment]
Yes, you're right @mrbuzz. Thanks!
