### ISSUE TITLE
suggest char::from_u32 over transmute::<u32, char>

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2099]
Thanks for the great talk @tomaka

**Comment by oli-obk** [comment]
We should also lint transmutes to bool and floats

**Comment by pizzaiter** [comment]
I would like to give this a try.

**Comment by mcarton** [comment]
@pizzaiter Great! Don't hesitate to open a PR even if it's not finished or to ask questions if you have any problem!
