### ISSUE TITLE
`needless_range_loop` lint

### ISSUE THREAD

**Issue by DarkEld3r** [rust-lang-nursery/rust-clippy#2106]
```rust
let data = [1; 100];
for i in 0..10 {
    println!("{}", data[i % 10]);
}
```
Clippy suggests the following: `for <item> in data.iter().take(10)` which is not an equivalent of the code above.

**Comment by oli-obk** [comment]
it actually is the same thing, but only because you used `10` twice ;)

In the case where the modulo and the array length are the same, the current suggestion is fine

If they differ, we probably need to suggest

```
    for i in data.iter().take(modulo).cycle().take(iteration_end) {
        println!("{}", i);
    }
```

**Comment by DarkEld3r** [comment]
Real [code](https://github.com/exonum/exonum/blob/master/exonum/benches/block.rs#L137) is a little more complicated (and hopefully less stupid). 😄
