### ISSUE TITLE
Forbid `if {foo; bar} {}`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2107]
That just opens the door for crazy "mutation in conditions" issues.

And I personally consider it totally unreadable

**Comment by llogiq** [comment]
I thought we already had a lint on that...like `block_in_if_condition_statement` and `block_in_if_condition_expression`, perhaps?

**Comment by oli-obk** [comment]
whoops

**Comment by oli-obk** [comment]
ppl on irc not using clippy... :(

**Comment by llogiq** [comment]
Now I really can say "happens to the best of us". 😄
