### ISSUE TITLE
Suggest `.and_then(f)` instead of `.map(f).unwrap_or(None)`

### ISSUE THREAD

**Issue by SuperCuber** [rust-lang-nursery/rust-clippy#2109]
Recently I've come accross this code in one of my projects:

```rust
get_some_option_value()
    .map(some_calculation_that_returns_option)
    .unwrap_or(None)
```

Since I wrote that, I learned a bit more about Option's api so I changed it to `.and_then`.

This is the kind of stuff I would expect clippy to tell me about, so I suggest adding a lint to catch this.

**Comment by oli-obk** [comment]
Should be easy enough. Probably just another branch in our method chain lint.
