### ISSUE TITLE
Suggest println!() instead of println!("")

### ISSUE THREAD

**Issue by sinkuu** [rust-lang-nursery/rust-clippy#2135]
`println!("")` and `prinln!()` both prints a `\n`, and the latter is better. `writeln!(out)` should also be suggested instead of `writeln!(out, "")`.

**Comment by MaloJaffre** [comment]
I would want to work on this, except if there is already someone on it.

**Comment by mcarton** [comment]
@MaloJaffre Go ahead! Don't hesitate to ask if you have any question.

**Comment by Phrohdoh** [comment]
> and the latter is better

How so?

**Comment by sinkuu** [comment]
IMHO `println!()` is easier to type and read than `print!("\n")`.

**Comment by Phrohdoh** [comment]
It is indeed easier to type and read by the "less characters" metric but isn't explicit (you have to know that the empty println macro prints \n).

**Comment by sinkuu** [comment]
One may not write `println!()` unless they know it, but how can they expect other behavior than printing `\n` by seeing it? I don't think that explicitness is so much important for this case. Moreover, clippy suggestions have informed users of language/library features that are often overlooked, and `println!()` seems like a fine addition to that.

**Comment by Phrohdoh** [comment]
Someone may expect `println!("\r\n")`...
