### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by wavded** [rust-lang-nursery/rust-clippy#2157]
It would be really nice to have report output (similar to `rustfmt`), thinking `checkstyle` (and perhaps others) in order have more detailed reporting in CI tools (like Jenkins).  Thoughts?

**Comment by oli-obk** [comment]
We reuse rustc's error reporting mechanism. You will be able to simplify the error reporting there via `--error-format=short`: https://github.com/rust-lang/rust/pull/44636

I don't think there's much we can do on our end. Reopen if you disagree

If specific lints are ugly/unreadable in the short format, it would be best to open individual issues for them

**Comment by wavded** [comment]
@oli-obk thx for the quick reply, I'll see what I can do with that.

**Comment by killercup** [comment]
@wavded you might also be able to consume rustc's json output and convert that to something like JUnit (or whatever your CI tool can parse).
