### ISSUE TITLE
should_implement_trait triggered on private method

### ISSUE THREAD

**Issue by vorner** [rust-lang-nursery/rust-clippy#2159]
Hello

Today, I created a struct with some public interface. Internally, I want to use it a *bit* like iterator, so I implemented a private `fn next(&mut self) -> Option<T>` helper method. This is on purpose to mimic the `Iterator` trait.

Clippy tells me that I should implement the trait. But that would make the `next` method effectively public interface, which I don't want.

In that sense, it seems like a false positive to me ‒ should the lint be triggered only on public methods if the trait is public? Or is my use case too odd?

To show the real code, here is the commit:
https://github.com/vorner/corona/commit/cb012273383aafccb394c12a4475a1b711f801e3#diff-40d2d23f45cd6212d2b8a20a61048c94R88

**Comment by oli-obk** [comment]
Yea, we shouldn't suggest to implement traits for private methods.
