### ISSUE TITLE
 clippy v0.0.166 build failed

### ISSUE THREAD

**Issue by xianghx** [rust-lang-nursery/rust-clippy#2167]
$ rustc --version
rustc 1.22.0-nightly (4279e2b4c 2017-10-21)
$ cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading clippy v0.0.166
  Installing clippy v0.0.166
 Downloading clippy_lints v0.0.166
   Compiling unicode-xid v0.0.4
   Compiling pulldown-cmark v0.0.15
   Compiling dtoa v0.4.2
   Compiling matches v0.1.6
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "/tmp/cargo-install.FSpQYHbyAa5T/release/build/pulldown-cmark-d9f1d2a4c12bd080/build_script_build-d9f1d2a4c12bd080.build_script_build0.rust-cgu.o" "-o" "/tmp/cargo-install.FSpQYHbyAa5T/release/build/pulldown-cmark-d9f1d2a4c12bd080/build_script_build-d9f1d2a4c12bd080" "/tmp/cargo-install.FSpQYHbyAa5T/release/build/pulldown-cmark-d9f1d2a4c12bd080/build_script_build-d9f1d2a4c12bd080.crate.allocator.rust-cgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-install.FSpQYHbyAa5T/release/deps" "-L" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-c3e4b79206c8c178.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_jemalloc-064a47d37dd9584c.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_system-7ab66d8b1dc07c88.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libpanic_unwind-b0a5f6f855a7ba6e.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librand-fb2e86da84f33f57.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libunwind-faa55fd0eab39cd3.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-ecf22eb28c6217ef.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-9e6751d60d680f40.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd_unicode-5335a01fae088e11.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-774d28f5c937ceca.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcompiler_builtins-d93d2b7f1f97a75d.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /tmp/cargo-install.FSpQYHbyAa5T/release/build/pulldown-cmark-d9f1d2a4c12bd080/build_script_build-d9f1d2a4c12bd080.build_script_build0.rust-cgu.o：在函数‘main’中：
          build_script_build0-cbe345300715aaa7a14176ca4901e8eb-exe.rs:(.text.main+0x23)：对‘std::rt::lang_start::ha6fd8df206a45d1d’未定义的引用
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `pulldown-cmark`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.166`, intermediate artifacts can be found at `/tmp/cargo-install.FSpQYHbyAa5T`

Caused by:
  build failed

**Comment by oli-obk** [comment]
can you try building `pulldown-cmark` manually from git? Maybe they have a fix for it?

**Comment by thomvil** [comment]
Build fails here too.

I get compilation errors for `clippy_lints`:
```
Compiling clippy_lints v0.0.166
error[E0061]: this function takes 5 parameters but 6 parameters were supplied
  --> /Users/_/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/escape.rs:74:29
   |
74 |         ExprUseVisitor::new(&mut v, cx.tcx, cx.param_env, region_scope_tree, cx.tables, None).consume_body(body);
   |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 5 parameters

error[E0061]: this function takes 5 parameters but 6 parameters were supplied
    --> /Users/_/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/loops.rs:1393:25
     |
1393 |     ExprUseVisitor::new(&mut delegate, cx.tcx, cx.param_env, region_scope_tree, cx.tables, None).walk_expr(body);
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 5 parameters

error[E0599]: no method named `rvalue_promotable_map` found for type `rustc::ty::TyCtxt<'_, '_, '_>` in the current scope
   --> /Users/_/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/methods.rs:841:14
    |
841 |             .rvalue_promotable_map(owner_def)
    |              ^^^^^^^^^^^^^^^^^^^^^

error[E0061]: this function takes 5 parameters but 6 parameters were supplied
   --> /Users/_/.cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/needless_pass_by_value.rs:111:38
    |
111 |             euv::ExprUseVisitor::new(&mut ctx, cx.tcx, cx.param_env, region_scope_tree, cx.tables, None).consume_body(body);
    |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 5 parameters

error: aborting due to 4 previous errors
```

**Comment by oli-obk** [comment]
@thomvil that's because your rustc is too old, please update to the latest nightly

**Comment by xianghx** [comment]
$ cargo install pulldown-cmark
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading pulldown-cmark v0.1.0
  Installing pulldown-cmark v0.1.0
   Compiling pulldown-cmark v0.1.0
   Compiling bitflags v0.9.1
   Compiling getopts v0.2.15
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m32" "-L" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "/tmp/cargo-install.Kc3cjDVSkCsN/release/build/pulldown-cmark-e68f0d6bac476023/build_script_build-e68f0d6bac476023.build_script_build0.rust-cgu.o" "-o" "/tmp/cargo-install.Kc3cjDVSkCsN/release/build/pulldown-cmark-e68f0d6bac476023/build_script_build-e68f0d6bac476023" "/tmp/cargo-install.Kc3cjDVSkCsN/release/build/pulldown-cmark-e68f0d6bac476023/build_script_build-e68f0d6bac476023.crate.allocator.rust-cgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-install.Kc3cjDVSkCsN/release/deps" "-L" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd-b28198482d35fe6f.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_jemalloc-eeddf60479570ffb.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc_system-5163d6a4327084bb.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libpanic_unwind-41def62daf8314bf.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/librand-2e4f6dfa46e61b79.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libunwind-fb8359c6d8db86c2.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liblibc-28639a0d55b7f761.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/liballoc-9494309cc460214e.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libstd_unicode-a12710302b9bdaba.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcore-9e60e3007121e41c.rlib" "/home/xianghx/.rustup/toolchains/nightly-i686-unknown-linux-gnu/lib/rustlib/i686-unknown-linux-gnu/lib/libcompiler_builtins-051f274ae4d99567.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /tmp/cargo-install.Kc3cjDVSkCsN/release/build/pulldown-cmark-e68f0d6bac476023/build_script_build-e68f0d6bac476023.build_script_build0.rust-cgu.o：在函数‘main’中：
          build_script_build0-76ecdb946cd3baa72b7248a6709c30f5-exe.rs:(.text.main+0x23)：对‘std::rt::lang_start::hadc5937ec0425732’未定义的引用
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `pulldown-cmark`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `pulldown-cmark v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-install.Kc3cjDVSkCsN`

Caused by:
  build failed

**Comment by xianghx** [comment]
$ cc --version
cc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by oli-obk** [comment]
Can you translate the linker errors for me? I can't read them

**Comment by oli-obk** [comment]
```
在函数‘main’中：
build_script_build0-76ecdb946cd3baa72b7248a6709c30f5-exe.rs:(.text.main+0x23)：对‘std::rt::lang_start::hadc5937ec0425732’未定义的引用
```

**Comment by xianghx** [comment]
In the function 'main':

Build_script_build0-76ecdb946cd3baa72b7248a6709c30f5-exe.rs: (.Text.main+0x23): undefined reference to 'std:: rt:: lang_start:: hadc5937ec0425732'

**Comment by oli-obk** [comment]
I think you should report this in `pulldown-cmark`, because we can't do anything on our end.

**Comment by xianghx** [comment]
Ok, thanks
