### ISSUE TITLE
Clippy "explicit_iter_loop" suggestion doesn't compile.

### ISSUE THREAD

**Issue by SuperCuber** [rust-lang-nursery/rust-clippy#2173]
I have the following code:
```rust
const GRID_SIZE: usize = 100;
const BYTES_PER_COLOR: usize = 3;

fn flatten(grid: [[[u8; BYTES_PER_COLOR]; GRID_SIZE]; GRID_SIZE]) -> Vec<u8> {
    let mut flat = Vec::new();

    for row in grid.into_iter() {
        for color in row.iter() {
            flat.extend_from_slice(color);
        }
    }

    flat
}
```

Clippy gives the following lint:
```rust
warning: it is more idiomatic to loop over references to containers instead of using explicit iteration methods
  --> src/pixel_render.rs:33:16
   |
33 |     for row in grid.into_iter() {
   |                ^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&grid`
   |
   = note: #[warn(explicit_iter_loop)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.166/index.html#explicit_iter_loop
```

After changing the code to the suggestion, it does not compile:
```rust
error[E0277]: the trait bound `&[[[u8; 3]; 100]; 100]: std::iter::Iterator` is not satisfied
  --> src/pixel_render.rs:33:5
   |
33 | /     for row in &grid {
34 | |         for color in row.iter() {
35 | |             flat.extend_from_slice(color);
36 | |         }
37 | |     }
   | |_____^ `&[[[u8; 3]; 100]; 100]` is not an iterator; maybe try calling `.iter()` or a similar method
   |
   = help: the trait `std::iter::Iterator` is not implemented for `&[[[u8; 3]; 100]; 100]`
   = note: required by `std::iter::IntoIterator::into_iter`
```

The real solution here is `grid.iter()`.

My suggestion: somehow check that the suggestion compiles before making it.

**Comment by oli-obk** [comment]
We should just bail out on arrays with more than 32 elements, they don't implement any traits

> My suggestion: somehow check that the suggestion compiles before making it.

That would be nice, but is really really hard

**Comment by SuperCuber** [comment]
@oli-obk yeah figured so, I guess the alternative is to not have lints that suggest noncompiling code :)

Didn't know arrays bigger than 32 didn't implement traits though, I think that's the thing that can be fixed by introducing integer parameters to generics?

**Comment by oli-obk** [comment]
> I guess the alternative is to not have lints that suggest noncompiling code :)

Yea I'm working on automating the detecting of bad suggestions ;) But it's nontrivial. See https://github.com/rust-lang/rust/issues/45516 for some thoughts

> I think that's the thing that can be fixed by introducing integer parameters to generics?

jup

**Comment by lukasstevens** [comment]
Unfortunately I am unable to reproduce this issue with the newest version of clippy. Can anyone confirm that this occurs with the newest version?
