### ISSUE TITLE
 no field `generics` on type `&rustc::hir::MethodSig`

### ISSUE THREAD

**Issue by xianghx** [rust-lang-nursery/rust-clippy#2183]
rustup update nightly
info: syncing channel updates for 'nightly-i686-unknown-linux-gnu'
229.5 KiB / 229.5 KiB (100 %) 159.2 KiB/s ETA:   0 s                
info: latest update on 2017-10-28, rust version 1.23.0-nightly (d9f124965 2017-10-27)

cargo install clippy
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing clippy v0.0.166
   Compiling regex-syntax v0.4.1
   Compiling either v1.3.0
   Compiling quine-mc_cluskey v0.2.4
   Compiling semver-parser v0.7.0
   Compiling getopts v0.2.15
   Compiling bitflags v0.9.1
   Compiling serde v1.0.16
   Compiling percent-encoding v1.0.0
   Compiling num-traits v0.1.40
   Compiling dtoa v0.4.2
   Compiling itoa v0.3.4
   Compiling quote v0.3.15
   Compiling matches v0.1.6
   Compiling pulldown-cmark v0.0.15
   Compiling unicode-normalization v0.1.5
   Compiling unicode-xid v0.0.4
   Compiling lazy_static v0.2.9
   Compiling clippy v0.0.166
   Compiling itertools v0.6.5
   Compiling semver v0.6.0
   Compiling unicode-bidi v0.3.4
   Compiling synom v0.11.3
   Compiling toml v0.4.5
   Compiling serde_json v1.0.4
   Compiling syn v0.11.11
   Compiling idna v0.1.4
   Compiling url v1.5.1
   Compiling serde_derive_internals v0.16.0
   Compiling serde_derive v1.0.16
   Compiling clippy_lints v0.0.166
   Compiling cargo_metadata v0.2.3
error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/lifetimes.rs:69:58
   |
69 |             check_fn_inner(cx, &sig.decl, Some(id), &sig.generics, item.span);
   |                                                          ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/lifetimes.rs:79:54
   |
79 |             check_fn_inner(cx, &sig.decl, body, &sig.generics, item.span);
   |                                                      ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/methods.rs:722:84
    |
722 |                    self_kind.matches(first_arg_ty, first_arg, self_ty, false, &sig.generics) {
    |                                                                                    ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/methods.rs:736:106
    |
736 |                     !self_kinds.iter().any(|k| k.matches(first_arg_ty, first_arg, self_ty, is_copy, &sig.generics)),
    |                                                                                                          ^^^^^^^^

error[E0609]: no field `generics` on type `&rustc::hir::MethodSig`
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/clippy_lints-0.0.166/src/new_without_default.rs:111:21
    |
111 |             if !sig.generics.ty_params.is_empty() {
    |                     ^^^^^^^^

error: aborting due to 5 previous errors

error: Could not compile `clippy_lints`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `clippy v0.0.166`, intermediate artifacts can be found at `/tmp/cargo-install.yeINcb97TcnS`

Caused by:
  build failed

**Comment by sinkuu** [comment]
#2140
