### ISSUE TITLE
Suggest simpler code in patterns

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang-nursery/rust-clippy#2201]
I've seen this that suggests a new feature to accept simple code in patterns:

https://github.com/rust-lang/rust/pull/45409

Is it a good idea to add a lint to Clippy to suggest those simplifications even in code that currently compiles?

**Comment by Manishearth** [comment]
Not until it stabilizes, no.

We already have a lint that goes in the opposite direction which we'll evolve into this I think.
