### ISSUE TITLE
Numeric literals that have a better representation in another format (65535 is 0xFFFF)

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2252]
I find `0xFFFF` to represent the meaning much more clearly than `65535`

More examples:

* `32773` => `0x8005`
* `32768` => `0x8000`
* `255` => `0xFF`

**Comment by clarcharr** [comment]
Related to #1775.

**Comment by flip1995** [comment]
I would like to try this as my first lint!

Should this lint only be applied for literals which are close to some power of 2? Or also for something like `0xFF00` instead of `65280`?

**Comment by oli-obk** [comment]
I think we're going to need both. Not sure how to nicely check for the `0xFF00` case though. Maybe convert all decimal literals to hex and check for lots of contiguous `F` or `0`?

**Comment by oli-obk** [comment]
the lint was created in #2362
