### ISSUE TITLE
unreadable_literal for hex numbers

### ISSUE THREAD

**Issue by nbaksalyar** [rust-lang-nursery/rust-clippy#2300]
I think that `unreadable_literal` rules should be different for hex numbers.
As an example, it suggests to replace `0xabcdef` with `0xab_cdef`, which arguably makes it less readable.

I would suggest to break hex numbers into groups of 4, then it will replace `0xabcdef01` with `0xabcd_ef01`, but leave `0xabcdef` as it is.

**Comment by oli-obk** [comment]
How about filling up with zeroes?

**Comment by clarcharr** [comment]
I think that filling up with zeroes is a good compromise.

**Comment by clarcharr** [comment]
I'm working on this.

**Comment by Nokel81** [comment]
Could this suggest to change `0xabcdef01` to `0x_abcd_ed01`? And with the filling with zeros: `0xabcdef` to `0x_00ab_cdef`?

**Comment by terry90** [comment]
I'm on it
