### ISSUE TITLE
Disable clippy for some modules and for the generated code from the build script

### ISSUE THREAD

**Issue by vityafx** [rust-lang-nursery/rust-clippy#2305]
How can I disable the clippy from checking the code in some module? For example, in my project I generate opengl bindings via `gl-generator` for later using in my code. The clippy always checks it but I wanna disable the checks for the code that I can't control.

**lib.rs**
```rust
mod gl;
```

**gl.rs**
```rust
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
```

**build.rs**
```rust
extern crate gl_generator;

use gl_generator::{Registry, Api, Profile, Fallbacks, GlobalGenerator};
use std::env;
use std::fs::File;
use std::path::Path;

fn main() {
    let dest = env::var("OUT_DIR").unwrap();
    let mut file = File::create(&Path::new(&dest).join("bindings.rs")).unwrap();

    Registry::new(Api::Gl, (4, 5), Profile::Core, Fallbacks::All, [])
        .write_bindings(GlobalGenerator, &mut file)
        .unwrap();
}
```

The compile output is about 500 errors in the generated `target/debug/out/binding.rs` file.

**Comment by Manishearth** [comment]
`#[allow(clippy)]` on the module declaration

**Comment by vityafx** [comment]
@Manishearth thank you! I don't know why I tried `deny`, lol.

**Comment by vext01** [comment]
@vityafx I just made the same mistake!

**Comment by AsadullahFarooqi** [comment]
is there any way to automate this? I mean where I don't have to manually add this `#[allow(clippy::all)]` in the auto-generated code. I just want clippy to ignore the whatever is in env: `OUT_DIR`directory
`let out_dir = env::var("OUT_DIR").unwrap();`

**Comment by AsadullahFarooqi** [comment]
@Manishearth

**Comment by stan-irl** [comment]
I dont understand what you're saying here. How can I add `#[allow(clippy)]` in the the auto-generated code if I dont own it?

It seems the only option is to set `#![allow(clippy)]` in gl.rs and disable clippy for the entire module, but if we want to put other code in there thats pretty undesirable.

Is that correct? I've been banging my head against the wall for a while now

**Comment by Manishearth** [comment]
> I dont understand what you're saying here. How can I add `#[allow(clippy)]` in the the auto-generated code if I dont own it?


_on_ the module, not _in_ the module.

>  but if we want to put other code in there thats pretty undesirable.

If you want the ability to control lint levels for generated code as a group, "don't do that", try to stick the generated data in its own module. It's pretty standard practice in Rust.

**Comment by stan-irl** [comment]
understood. 

my problem is that im using a macro to generate FFI scaffolding for a set of functions I want to expose. Rhe scaffolding has to be included in the same module as the function declarations. This means that my own code can only be as strict as the generated code because they are forced to live in the same module.

**Comment by Manishearth** [comment]
I don't think there's anything I can do for you then.

**Comment by stan-irl** [comment]
no worries. thanks for clarifying
