### ISSUE TITLE
Add suggestion to print_with_newline

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rust-clippy#2319]
This code

```rust
fn main() {
    println!("");
}
```

currently (clippy 0.0.177) triggers this:

```
warning: using `println!("")`, consider using `println!()` instead
 --> src/main.rs:2:5
  |
2 |     println!("");
  |     ^^^^^^^^^^^^^
  |
  = note: #[warn(print_with_newline)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.177/index.html#print_with_newline
```

where the suggested replacement is only in the `warning:` line, but is not a true, auto-applicable suggestion.

**Comment by hwiechers** [comment]
Why is changing `println!("")` to `println!()` not applicable?

**Comment by killercup** [comment]
It's not *auto*~applicable by rustfix because the lint doesn't use
`span_suggestion`.

Henri Wiechers <notifications@github.com> schrieb am Do. 4. Jan. 2018 um
05:18:
