### ISSUE TITLE
Why is shadow_reuse a clippy-pedantic lint?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rust-clippy#2322]
The docs say:

> Why is this bad?
>
> Not too much, in fact it’s a common pattern in Rust code. Still, some argue that name shadowing like this hurts readability, because a value may be bound to different things depending on position in the code.

But for me at least `shadow_reuse` is not only a common pattern in Rust code, but actually idiomatic Rust.

If there is a group of people that thinks a pattern hurts readability, the lint should exist, but if there is also a group of people that thinks this pattern is actually idiomatic Rust, then the lint shouldn't be in `clippy-pedantic`.

**Comment by oli-obk** [comment]
Yea, we should move it to the restrictions list

**Comment by phansch** [comment]
Looks like this was done with https://github.com/rust-lang-nursery/rust-clippy/pull/2579

Going ahead and closing this.
