### ISSUE TITLE
Lint suggestion: Warn if non-trivial work is done inside .expect

### ISSUE THREAD

**Issue by Rufflewind** [rust-lang-nursery/rust-clippy#2338]
Suggestion: It would be useful to issue warnings for cases like `.expect(&format!(…))` that, although correct, are often slower than one would expect because the `format!` occurs regardless of whether the error message is needed.

**Comment by oli-obk** [comment]
This is a natural extension to the [`or_fun_call`](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#or_fun_call) lint

**Comment by theotherphil** [comment]
I'd like to have a go at this.

**Comment by oli-obk** [comment]
This has been fixed in #2815
