### ISSUE TITLE
Add check: unnamed constants (magic numbers)

### ISSUE THREAD

**Issue by vityafx** [rust-lang-nursery/rust-clippy#2342]
I'd like to propose adding an optional check for unnamed constant (magic numbers) used in the code. This is a bad practice even according to the [wikipedia](https://en.wikipedia.org/wiki/Magic_number_(programming)).

```rust
let i = 3; // Unnamed constant

if i > 5 { // Unnamed constant
    print!("1");
}
```

What do you think?

**Comment by killercup** [comment]
dupe of #1539, sorry

**Comment by vityafx** [comment]
@killercup Yes, I have already found it too. Excuse me.
