### ISSUE TITLE
False positive: documentation required for `fn main()`

### ISSUE THREAD

**Issue by H2CO3** [rust-lang-nursery/rust-clippy#2348]
Hey, and thanks for making Clippy!

Today I've run across a slight inconvenience: when the `missing_docs_in_private_items` lint is enabled in an executable crate, it wants me to document `fn main()` too. I think it would be safe to assume that this is a function that does not need to be documented, because its semantics are defined by the language.

**Comment by Manishearth** [comment]
https://github.com/rust-lang-nursery/rust-clippy/pull/2349

**Comment by Manishearth** [comment]
Thanks for reporting!

**Comment by H2CO3** [comment]
Wow, that was quick. 🍾
