### ISSUE TITLE
Broken suggestion for const_static_lifetime

### ISSUE THREAD

**Issue by killercup** [rust-lang-nursery/rust-clippy#2365]
The suggestion for const_static_lifetime currently only removes `'static` from `&'static str` and leaves a space between `&` and `str`.

cf. https://github.com/killercup/rustfix/pull/49

**Comment by killercup** [comment]
https://github.com/rust-lang/rust/pull/47465 reminded of this (and that I never documented it)

**Comment by Manishearth** [comment]
https://github.com/rust-lang-nursery/rust-clippy/pull/2366
