### ISSUE TITLE
Bad suggestion for removing `&` patterns

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2414]
`rustfix` idenfied an issue and suggested to replace `self` with `*self` to avoid `&` in each match type.

```
Info: you don't need to add `&` to all patterns
  --> decline_reason_code.rs:26:9-34:10

instead of prefixing all patterns with `&`, you can dereference the expression
[0]: Replace:

            match self {
            &DeclineReasonCode::UnsuccessfulDetok => "0390",
            &DeclineReasonCode::TokenNotFound => "0391",
            &DeclineReasonCode::AuthExpired => "0392",
            &DeclineReasonCode::TokenNotActive => "0393",
            &DeclineReasonCode::TokenExpired => "0394",
            &DeclineReasonCode::None => "",

        }

with:

    match *self { .. }
==> What do you want to do? [0-9] | [r]eplace | [s]kip | save and [q]uit | [a]bort (without saving)
  > r
Suggestion accepted. I'll remember that and apply it later.
```

Original Code:
```
pub fn as_str(&self) -> &'static str {
        match self {
            &DeclineReasonCode::UnsuccessfulDetok => "0390",
            &DeclineReasonCode::TokenNotFound => "0391",
            &DeclineReasonCode::AuthExpired => "0392",
            &DeclineReasonCode::TokenNotActive => "0393",
            &DeclineReasonCode::TokenExpired => "0394",
            &DeclineReasonCode::None => "",

        }
    }
```

Replaced code after applying `rustfix` suggestion:

```
pub fn as_str(&self) -> &'static str {
        match *self { .. }
    }
```

Thanks @rohitjoshi for finding it

**Comment by oli-obk** [comment]
To anybody fixing this: Please create a multi-suggestion instead of one huge one.

**Comment by killercup** [comment]
label: Good-first-issue :)

https://github.com/rust-lang-nursery/rust-clippy/blob/8123495e0f36c429a865645a15a2bbb02e9a0c0f/clippy_lints/src/matches.rs#L403-L435

**Comment by oli-obk** [comment]
At this point I'd like to thank @killercup for volunteering to mentor this issue ;)

Building multi-suggestions is a little more complex, for an example look at

https://github.com/rust-lang-nursery/rust-clippy/blob/26c415ab2d9c9c3ab27ca4358bebe21131a83047/clippy_lints/src/types.rs#L1683-L1706

which generates two suggestions by placing them into a `Vec`

**Comment by killercup** [comment]
Sure, I'd be happy to mentor this. Mentoring times are a bit restricted, though: I can only offer this Sunday from 16:00 to 17:00 (UTC+1) whilst sitting right across from @oli-obk at FOSDEM (so I can forward all the hard questions)! ;)

- - -

If nobody needs mentoring at that time I might start a draft of a nicer Diagnostics API… If you like builders more than a function with ~12 parameters then I hope this is looking good:

```rust
USELESS_VEC::trigger(span)
    .msg("optional because maybe use default message")
    .add(Suggestion::for_span(span)
        .suggest("[42]")
        .help("it's the right answer"))
    .draw(context)
```

Similarly, I'd convert this multispan_sugg monster to something like

```rust
IMPLICIT_HASHER::trigger(span)
    .msg(format!("impl for `{}` should be generalized over different hashers", target.type_name()))
    .add(SuggestionGroup::titled("consider adding a type parameter")
        .add(Suggestion::for_span(generics_suggestion_span).suggest(format!(…)))
        .add(Suggestion::for_span(target.span()).suggest(format!(…)))
    .draw(cx)
```

**Comment by kimsnj** [comment]
I'll give this issue a try.
I sadly won't be available the mentoring session on Sunday, but there are enough hints in your comments to get me started.
