### ISSUE TITLE
clippy prints suggestions in a different style than the source material

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang-nursery/rust-clippy#2422]
Functionally this is not an issue it is just me pointing out a papercut.

My code is as follows:

```rust
impl From<walkdir::Error> for Error {
    fn from(e: walkdir::Error) -> Self {
        let path = e.path()
            .map(|ref_path| ref_path.to_string_lossy().to_string())
            .unwrap_or(String::from("<unknown path>"));

        Error::PathNotFound { path }
    }
}
```

clippy helpfully suggests I use `unwrap_or_else`:

```rust
help: try this
    |
165 |         let path = e.path()
166 |             .map(|ref_path| ref_path.to_string_lossy().to_string()).unwrap_or_else(|| String::from("<unknown path>"));
    |
```

You can see that the `.unwrap_or_else` was printed on the same line as my `.map` instead of the following line.

---

Version information:

```
$ cargo -V
cargo 0.24.0 (45043115c 2017-12-05)

$ rustc -V
rustc 1.23.0 (766bd11c8 2018-01-01)

$ cargo +nightly clippy -- -V
0.0.184
```

**Comment by oli-obk** [comment]
Yea, this is pretty hard to do right. In some cases we can try replacing smaller code regions (and thus preserving whitespace outside those regions), but mostly we need to punt to rustfmt.

**Comment by oli-obk** [comment]
In this case should just fix the span of this suggestion by making it only change the `unwrap_or(` to `unwrap_or_else(|| ` instead of replacing the entire method call.

**Comment by bootandy** [comment]
Hi, I'm new to this project but I thought I'd take a look at this. - To fix this would require decreasing the span used here: https://github.com/rust-lang-nursery/rust-clippy/blob/master/clippy_lints/src/methods.rs#L894 yes?
