### ISSUE TITLE
single-match lint expands println! macro in suggestion

### ISSUE THREAD

**Issue by kimsnj** [rust-lang-nursery/rust-clippy#2455]
The example in the README file:

``` rust
    let x = Some(1u8);
    match x {
        Some(y) => println!("{:?}", y),
        _ => ()
    }
```

produces this suggestions:

```
help: try this: `if let Some(y) = x { $ crate :: io :: _print ( format_args ! ( $ ( $ arg ) * ) ) }`
```
Using current master (commit: 6b3487a916b22312cc67fef0d3ec49985fc1197b)
And rustc 1.25.0-nightly (b8398d947 2018-02-11)

Note putting the statement inside a block `{ println!("{:?}", y) }` works properly (and is the current case covered by ui tests).

**Comment by kimsnj** [comment]
The issue seems to be more general than just the single arm lint. for example:
```
4 | /     match x {
5 | |         true => {println!("yay")},
6 | |         false => println!("nay")
7 | |     }
  | |_____^ help: consider using an if/else expression: `if x {println!("yay")} else { $ crate :: io :: _print ( format_args ! ( $ ( $ arg ) * ) ) }`
```
The difference in behaviour between the two arms can be observed by directly calling `utils::snippet` with either `arms[0].body.span` or `arms[1].body.span`.
This calls a method on `LintContext` session…

Can this be fixed on clippy side or should it be on rustc ?
I am not quite sure where to go from here.

**Comment by oli-obk** [comment]
We should be checking the `span` for macro expansions and not produce a snippet in that case (or change it to `approximate_suggestion` and insert a placeholder
