### ISSUE TITLE
force full re-clippy

### ISSUE THREAD

**Issue by davemilter** [rust-lang-nursery/rust-clippy#2498]
I want run `clippy` on my CI server and get every time all warnings, 
not only in changed projects.
Also I want to cache "target" directory between run of `cargo build`,
because of compilation too slow.

But I don't see how it possible with current clippy:

```sh
$ cargo +nightly clippy
warning:
warning:
warning:
$ cargo +nightly clippy
$ lib: foo
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
test: test_foo
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
```
as you see the second run of `clippy` gives nothing,
And there is no option like `--force`, as workaround I use `find . -name "*.rs" -exec touch {} \;`,
it is better then remove `target` or `cargo clean`, but still cause also rebuild of crate in the next `cargo +nigtly test`

**Comment by birkenfeld** [comment]
Yep, this is annoying - the purpose of running a linter is to emit lints on every run :)

**Comment by lnicola** [comment]
Did https://github.com/rust-lang-nursery/rust-clippy/pull/2582 fix this?

**Comment by oli-obk** [comment]
My local tests say yes. Reopen a new issue if it persists on your system

**Comment by dessalines** [comment]
This is still an issue.

**Comment by simnalamburt** [comment]
Me too. Is there any explicit options to force re-run?

**Comment by flip1995** [comment]
tracked in #4612 

on nightly you can use `cargo clippy -Zunstable-options`
