### ISSUE TITLE
unnecessary parentheses around range literals

### ISSUE THREAD

**Issue by llogiq** [rust-lang-nursery/rust-clippy#251]
I recently noticed that range literals don't need parentheses, unless their methods are used.

I think that getting rid of those unneeded parenthesis makes for less cluttered, thus more readable code.

However, I'd be fine to Allow by default. Thoughts?

**Comment by TimNN** [comment]
Considering that the only lints marked as allow by default are those which are prone to warn about intended behaviour as far as I can tell, I would vote for making the lint Warn by default.

**Comment by birkenfeld** [comment]
I thought there was an "unneeded parens" lint in rustc already, but it only covers the expression for if, for, etc. where C people might put parens out of habit. So +1 for this.

**Comment by llogiq** [comment]
OK so this is basically an extension of a known compiler lint. Perhaps we should ask the compiler guys if they want to include it.

**Comment by Manishearth** [comment]
Yeah, that sounds like the right approach here

**Comment by llogiq** [comment]
Btw. parentheses around ranges are always unnecessary, because ranges bind stronger than function calls. However, I think that if we have a method call, the parentheses make it more clear that the method call has the range as first argument.

So in fact we could have three lints, two of which can be `Allow` by default:

* `paren_range` match plain parenthesized ranges (e.g. `(1..10)` as in `for x in (1..10) { .. }`), `Warn` by default (otherwise extend `unused_parens`)
* `paren_method_range` match parenthesized ranges on which a method is called, e.g. `(1..10).step_by(2)`, `Allow` by default
* `precedence_range` match *un*parenthesized ranges on which a method is called, e.g. `1..10.step_by(2)` because it may confuse people into thinking that `10` has a `step_by(..)` method. `Allow` by default

I believe the first one should actually be built into `rustc` itself (I'll open an issue).

**Comment by Manishearth** [comment]
IMO we should organize our lint groups more (perhaps start mentioning lint groups in the lint declaration and have the python script generate them). Have some "normal" (group: clippy) `Warn` lints, have some "zealous" (group: clippy_zealous) `Allow` lints, and then some "clippy_misc" lints for stuff like the above where the lints actually conflict

**Comment by birkenfeld** [comment]
> Btw. parentheses around ranges are always unnecessary, because ranges bind stronger than function calls.

Really? This doesn't seem to compile: `0..10.step_by(2)`

This would also be bad in slices where you often do something like `vec[0..vec.len()]`...

**Comment by llogiq** [comment]
Ah, I had only looked at `rustc -Z ast_json` without checking if it actually compiles. My bad.

See [Rust issue #28121](https://github.com/rust-lang/rust/issues/28121). We may still decide to develop it here and merge it into rustc later, for speed of development.

**Comment by oli-obk** [comment]
rustc requires an RFC for such a lint. It would be good to implement it in clippy to have some data to show in the RFC

**Comment by llogiq** [comment]
AFAIK rustc lints this for some time now. Closing.
