### ISSUE TITLE
Suggestion: run clippy for specific package in workspace

### ISSUE THREAD

**Issue by bjgill** [rust-lang-nursery/rust-clippy#2518]
We now have the `--all` option, and this is very helpful when testing a workspace.

However, when developing, it would be convenient to be able to run clippy over only a specified package in the workspace. i.e. similar to the `cargo test` option `-p SPEC, --package SPEC ...  Package to run tests for`.

Unless anyone objects, I'll have a look at implementing this - it should be a fairly simple extension of the current handling for `--all`.

**Comment by bjgill** [comment]
I've started prototyping. It looks as if `cargo` is busy transitioning over to use [`clap`](https://github.com/kbknapp/clap-rs) - see https://github.com/rust-lang/cargo/issues/4177. Do we want to do the same? 

I think we would end up with a help message like that below (c.f. the current one at https://github.com/rust-lang-nursery/rust-clippy/blob/master/src/main.rs#L14).

Thoughts? It'll be a minor functional change (you can no longer specify `--all` anywhere - it must be at the start), and the help message will look different (though I could probably retain the old look if that is desirable). We'll gain, however, since `main.rs` will no longer need to parse the contents of `std::env::args()`, instead relying on `clap`.

```
Clippy 0.0.188
Checks a package to catch common mistakes and improve your Rust code.

USAGE:
    cargo-clippy [OPTIONS] [--] [CMD]...

OPTIONS:
        --all                  Run over all packages in the current workspace
    -h, --help                 Prints help information
    -p, --package <SPEC>...    Package(s) to check
    -V, --version              Prints version information

ARGS:
    <CMD>...    Commands to pass through to cargo rustc

Other options are the same as `cargo rustc`.

To allow or deny a lint from the command line you can use `cargo clippy --`
with:

    -W --warn OPT       Set lint warnings
    -A --allow OPT      Set lint allowed
    -D --deny OPT       Set lint denied
    -F --forbid OPT     Set lint forbidden

The feature `cargo-clippy` is automatically defined for convenience. You can use
it to allow or deny lints from the code, eg.:

    #[cfg_attr(feature = "cargo-clippy", allow(needless_lifetimes))]
```

**Comment by oli-obk** [comment]
yes please! no more args parsing!

**Comment by mimoo** [comment]
not sure why this was closed, it looks like you still can't run clippy on a specific package in your workspace

**Comment by ebroto** [comment]
@mimoo could you share an example of what does not work for you? `cargo clippy -p <package>` should work with both simple and virtual workspaces.

If you refer to the ability of running Clippy only on the package, excluding its dependencies (#3025), that will be fixed in a couple of days after rust-lang/cargo#8758 is merged.

**Comment by mimoo** [comment]
Ah, indeed I was getting hits on its dependencies (which are other packages in my workspace) and didn't understand why

**Comment by mleonhard** [comment]
If one package depends on another package the workspace, clippy will still check the extra package.  To avoid that, pass the  `--no-deps` flag ([recently added](https://github.com/rust-lang/rust-clippy/pull/6188)).  With this flag, you can even run clippy in the crate directory and it will check only that crate:

```
$ cd workspace1/crate1/
$ cargo clippy --all-features -- -D clippy::pedantic --no-deps
```

If you run clippy as part of a script that runs other cargo commands, clippy may just exit right away without reporting any errors.  The workaround is to clean the package just before running clippy:
```
$ cd workspace1/crate1/
$ cargo clean --package "$(basename "$PWD")"
$ cargo clippy --all-features -- -D clippy::pedantic --no-deps
```
