### ISSUE TITLE
Target stable rather than nightly

### ISSUE THREAD

**Issue by mcandre** [rust-lang-nursery/rust-clippy#2527]
Could clippy start targeting stable release versions of Rust, so that developers can use clippy without having to constantly update versions?

**Comment by oli-obk** [comment]
Sorry that's not really possible in the near future

It is planned to distribute clippy along with the stable compiler via rustup. Should be ready some time this year

**Comment by Manishearth** [comment]
Clippy directly plugs into the compiler to work, whose guts are not and will never be stable.
