### ISSUE TITLE
Underscores only every three digits in decimal literals

### ISSUE THREAD

**Issue by l0b0** [rust-lang-nursery/rust-clippy#2537]
If every localization (counter-examples welcome!) inserts separators only between the third and fourth decimal digits, sixth and seventh digits, etc from the least significant digit (that is, "12,345,678" but never "1234,5678" or "12,34,56,78"), should there be a lint to enforce this? `inconsistent_digit_grouping` is good, but it won't catch `1234_5678` or `12_34_56_78` (unless it's documented wrong; `cargo clippy` won't run right now).

**Comment by Manishearth** [comment]
This varies a lot between localizations -- India does numbers as 1,00,00,00,000 and Chinese numbers conceptually have the comma on the 10,000s place (万). I don't think it carries over to being used with non-chinese numerals though.

**Comment by l0b0** [comment]
Thanks @Manishearth, how's this?

**Comment by Manishearth** [comment]
You can't guess the locality of the programmer. Nor should Clippy try.

**Comment by l0b0** [comment]
That's why it should be a configurable value, as mentioned.

**Comment by Manishearth** [comment]
Oh, I see. I still disagree -- the configurable values should be for improving the experience, not fixing it. (doc_markdown is an exception to this but I have reservations with it anyway).

Besides, I can easily see reasons to split them at other points for conveying other information. I do not see a strong reason to enforce decimal separators.

**Comment by l0b0** [comment]
Isn't that why this would be optional? In 15 years programming I've never come across a decimal number where splitting anywhere other than between thousand(th)s would make sense. It would be great to see more opinions on this before closing it as not useful.

**Comment by Manishearth** [comment]
I mean, yeah, allow by default would be kinda okay, but still, I don't really consider this to be a lint we need.

If others want this too the issue can be reopened.
