### ISSUE TITLE
alloc::range::RangeArgument → core::ops::RangeBounds

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang-nursery/rust-clippy#2552]
https://github.com/rust-lang/rust/pull/49163 proposes renaming and moving this trait, and Clippy contains:

```rust
src/tools/clippy/tests/ui/needless_pass_by_value.rs
118:// whitelist RangeArgument
119:fn range<T: ::std::collections::range::RangeArgument<usize>>(range: T) {

src/tools/clippy/clippy_lints/src/utils/paths.rs
58:pub const RANGE_ARGUMENT_TRAIT: [&str; 3] = ["alloc", "range", "RangeArgument"];
```

The former will likely only cause a deprecation warning, but the latter line might need to be updated top preserve lint behavior.

**Comment by Manishearth** [comment]
https://github.com/rust-lang-nursery/rust-clippy/pull/2589
