### ISSUE TITLE
inconsistent_digit_grouping: some inconsistent groupings are allowed

### ISSUE THREAD

**Issue by barafael** [rust-lang-nursery/rust-clippy#2553]
A literal which appears inconsistent to me is accepted by clippy:

https://play.rust-lang.org/?gist=7f2db0df838ddcc3d7cbe6200dfbf064&version=undefined

I am not sure if this is intentional, so I thought I'd report.

**Comment by oli-obk** [comment]
Yea this is intentional. We don't know the locale of the user and we should not be using it if we did. iirc chinese number splitting is done this way.
