### ISSUE TITLE
.clippy.toml support (with leading dot)

### ISSUE THREAD

**Issue by pravic** [rust-lang-nursery/rust-clippy#2563]
Is it supported? 

If no, is it worth to do it? Also to make it consistent with `rustfmt.toml` which allows `.rustfmt.toml` as well.

**Comment by oli-obk** [comment]
I don't think we support it. Should be easy enough to check for a second file.

**Comment by pravic** [comment]
It is supported: https://github.com/rust-lang-nursery/rust-clippy/blob/b835877d2ecba1b91ac74fee5b042ac0673aff14/clippy_lints/src/utils/conf.rs#L184-L187

Then it is worth to mention in the README.md, like:

> Some lints can be configured in a TOML file named `clippy.toml` or `.clippy.toml`.

Thanks!

**Comment by oli-obk** [comment]
Indeed. The issue label then still applies ;)

**Comment by CYBAI** [comment]
@oli-obk @pravic  I'd like to open a PR to update the README!
