### ISSUE TITLE
Failing cargo clippy commands that used to work

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2568]
Overnight some of my Travis builds started failing in `cargo clippy` commands. I see that there has not been a Clippy release today so this must be due to a Cargo or Rust change.

Indeed as of rustc 1.26.0-nightly (c08480fce 2018-03-23), just running `cargo clippy` in [this directory](https://github.com/serde-rs/serde/tree/master/serde) fails with "error: multiple input filenames provided".

Filing here in the hope that you would know where this may be breaking.

---

https://travis-ci.org/serde-rs/serde/jobs/357665015

```
error: Unrecognized option: 'features'

error: Could not compile `serde`.
```

https://travis-ci.org/dtolnay/serde-yaml/jobs/357723179

```
error: multiple input filenames provided

error: Could not compile `serde_yaml`.
```

**Comment by matthiaskrgr** [comment]
Hi, looks like a duplicate of #2566

**Comment by dtolnay** [comment]
Indeed, thanks!
