### ISSUE TITLE
Link to official version of internal API documentation in contributing.md

### ISSUE THREAD

**Issue by phansch** [rust-lang-nursery/rust-clippy#2591]
The CONTRIBUTING.md currently links to http://manishearth.github.io/rust-internals-docs in two places. 

Once ~~https://github.com/rust-lang/rust-central-station/pull/40~~ is merged, there will be a stable location for the internal API documentation and we should link to that instead.

~~The new API docs will be at https://doc.rust-lang.org/nightly-rustc~~

**Comment by phansch** [comment]
The new docs are now live at https://doc.rust-lang.org/nightly/nightly-rustc/rustc/. With https://github.com/rust-lang-nursery/rust-clippy/commit/c170e8640349657c054c16132be37417c9289948 there is only one link left that will have to be fixed :+1:

**Comment by Manishearth** [comment]
https://github.com/rust-lang-nursery/rust-clippy/commit/1c73db172a59ff4e34b3bc636614029401e66a7a
