### ISSUE TITLE
print-literal downside

### ISSUE THREAD

**Issue by mikerite** [rust-lang-nursery/rust-clippy#2617]
The new print-literal lint has this warning.

> /// **Known problems:** Will also warn with macro calls as arguments that expand to literals
> /// -- e.g., `println!("{}", env!("FOO"))`.

I don't understand how this is a downside. Surely the change from
`println!("{}", env!("FOO"))` to `println!(env!("FOO"))` is better for all the same reasons as a regular literal. This was discussed in the pull request #2608 but I don't get it.

**Comment by oli-obk** [comment]
uuuuh... that is a very good point.

Als long as the suggestion suggests that and not `println!("value_of_FOO")` that's the correct solution

**Comment by sinkuu** [comment]
Doing this requires that `{` and `}`s in the environmental variable are escaped, which might not be applicable in general.

**Comment by mikerite** [comment]
Ok, that makes sense.
