### ISSUE TITLE
new lint: useless clone

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#2649]
````rust
    let a = String::from("Hello world");
    let b = a.clone();
    println!("{}", b);
````
If we have an object a
make a clone of it: b
and then do something with b (but nothing else with a)
I think the clone is redundant since we could have just done our operation (println!()) with object a in the first place, especially since both are immutable.
If there is mutability this might be more tricky, to reason about.

**Comment by darnir** [comment]
I think this is similar to #17

**Comment by oli-obk** [comment]
Closing as duplicate
