### ISSUE TITLE
Explicitly mark lints as nightly only?

### ISSUE THREAD

**Issue by darnir** [rust-lang-nursery/rust-clippy#2652]
While I understand that `clippy` is a nightly-only project. It is used by many people who want to target only stable. I usually compile clippy against the latest nightly, run it and fix any issues it points out, but eventually use my code only against the stable Rust branch.

Recently I noticed that clippy was giving me some warnings which are valid only for nightly code. For example, there is the `range_plus_one` lint which suggests using the inclusive range syntax: `a..=b`. However, this is experimental and hence nightly only. There seem to be no warnings about this either in the documentation or in the warning itself.

Would it be possible to mark these lints in the documentation such that we know that the suggestion will not work on Stable? It would be even better if there could be a line in the warning Clippy prints stating that this is an experimental / nightly only feature

**Comment by oli-obk** [comment]
That lint should be in the nursery group until stable supports that feature

**Comment by darnir** [comment]
https://github.com/rust-lang-nursery/rust-clippy/blame/4015395888308a4496f6931e66c492f672e3663f/clippy_lints/src/ranges.rs#L58

This seems to show that the lint is already in the nursery group. Or is there some other change that is required?

**Comment by darnir** [comment]
Okay, so as it turns out, the "nursery" group of lints is not marked specially anywhere. They are all under "default-allow", but nowhere in the documentation is it mentioned that these lints may be nightly-only. 

When I see a lint in Clippy marked as "allow" by default, I interpret it as, "this is not incorrect but may be something I want to keep a track of". So I guess, the original request still holds, please add this information somewhere to the documentation

**Comment by oli-obk** [comment]
We have plans to show the lint groups in the docs. cc @killercup

**Comment by oli-obk** [comment]
@darnir how do you like the docs now? https://rust-lang-nursery.github.io/rust-clippy/master/index.html

**Comment by darnir** [comment]
@oli-obk That looks nice! Thanks for fixing it up this quick.

I haven't checked, but is there any place that actually explains what the nursery lint gecause it may not be so obvious otherwise.

**Comment by oli-obk** [comment]
Nope there isn't, adding it now :)
