### ISSUE TITLE
Warn on extraneous, unnecessary semicolons 

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/rust-clippy#266]
``` rust
fn main() {
    ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    println!("Hello, world!");
}
```

**Comment by Manishearth** [comment]
I'm not sure how to do this, `ast-json` on that code gives nothing checkable (the semicolons are parsed out?)

There are still ways of doing this though.

**Comment by llogiq** [comment]
We'd need to look at the actual code (via snippet) if available.

**Comment by sanmai-NL** [comment]
Can we close this and approach this as a `rustfmt` concern instead?

**Comment by oli-obk** [comment]
Yea I agree, this should be solved by rustfmt
