### ISSUE TITLE
Infallible match using `match` instead of `let`

### ISSUE THREAD

**Issue by idubrov** [rust-lang-nursery/rust-clippy#2671]
I had a code where I used enum with a single variant (it was created for serialization purposes, so enum literal name could be used as a "tag field").

When deconstructing, I used match as in the following snippet:
```
pub enum Data {
  Datum(&'static str)
}

#[test]
pub fn test() {
  let data = Data::Datum("hello");
  // deconstructing
  let datum = match data {
    Data::Datum(s) => s,
  };
  println!("{}", datum);
}
```

However, it would make more sense to just use `let`, like this:

```
pub enum Data {
  Datum(&'static str)
}

#[test]
pub fn test() {
  let data = Data::Datum("hello");
  let Data::datum(datum) = data; // deconstructing!
  println!("{}", datum);
}
```

Do you think this would be a reasonable lint?

**Comment by 17cupsofcoffee** [comment]
Assuming nobody else has beaten me to it, might I be able to work on this issue? :)

**Comment by oli-obk** [comment]
it's all yours!
