### ISSUE TITLE
Automatic fixing of issues with rerast

### ISSUE THREAD

**Issue by kornelski** [rust-lang-nursery/rust-clippy#2688]
[`rerast`](https://github.com/google/rerast) can find and replace code in Cargo projects. It's based on AST and is type-aware, so it can handle even complex transformations correctly. It supports "rule files", so specific sets of replacements can be written once and shared.

Would you be interested in integrating with rerast?

For example, the lint about using `u32::from(c)` instead of `c as u32` can be fixed automatically. I imagine that [Clippy's help page for that lint](https://rust-lang-nursery.github.io/rust-clippy/v0.0.194/index.html#cast_lossless) could include a rerast rule for that change. Or, even more adventurously, there could be `cargo clippy --fix` that runs it.

**Comment by mcarton** [comment]
Clippy already tries to use rustc built-in suggestions when possible, which works well with [`rustfix`](https://github.com/rust-lang-nursery/rustfix). Looks like `rerast` solves a slightly different problem.
