### ISSUE TITLE
update the rustc submodule

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2700]
I won't get to it anytime soon. All that's needed is to point the submodule (src/tools/clippy) in the rustc repo to the master branch of this repo and run the x.py script to update the Cargo.lock and open a pr with said changes

**Comment by phansch** [comment]
Will give this a try today :+1:

**Comment by phansch** [comment]
This would require a new clippy release, no?
I manged to update the submodule, but running `cargo update -p clippy` makes no changes

**Comment by oli-obk** [comment]
Should be fine. Releases of submodules make no difference if no dependencies changed. Try running. /x.py without any args (after git add-ing the submodule).
