### ISSUE TITLE
add a build script that complains about wrong nightly versions

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2716]
Similar to what rocket has. Since we don't know what future rustc versions are OK, we just emit an error message if the rustc version is too old

**Comment by phansch** [comment]
I suppose that this is the build script, right? https://github.com/SergioBenitez/Rocket/blob/master/lib/build.rs

**Comment by oli-obk** [comment]
jup. we should probably read the version numbers from an extra file with include_str (instead of hardcoding in the build.rs) so we can just generate the current version number via the update_lints python script

**Comment by phansch** [comment]
Going to take a look at this now and hope to have something merge-ready by next week :+1:
