### ISSUE TITLE
Run Clippy over various crates in new travis build

### ISSUE THREAD

**Issue by phansch** [rust-lang-nursery/rust-clippy#2736]
It would be nice to have a way to run clippy over a bigger rust codebase than just our tests on Travis/AppVeyor.
We could start by running Clippy over a couple of crates in a separate CI job and ensure that `cargo clippy` does not cause an ICE in any of the crates.

This would also allow us to detect breaking changes inside clippy before we do a release.

To close this issue, the following crates should be checked:

Crates to include:
* [ ] futures-rs
* [x] rand
* [ ] failure
* [ ] rustfmt
* [ ] log
* [ ] chalk
* [ ] nom
* [ ] stdsimd
* [x] cargo
* [ ] serde
* [ ] chrono

**Comment by oli-obk** [comment]
crates like `serde` do not trigger any clippy lints, so we can even check those for new lint occurrences.

We should probably start this out as a travis job that is allowed to fail.
