### ISSUE TITLE
lint on impl Trait returned from public function

### ISSUE THREAD

**Issue by diwic** [rust-lang-nursery/rust-clippy#2756]
Hi, 

As per discussion [here](https://www.reddit.com/r/rust/comments/8ik620/notes_on_impl_trait/dysy9cw/) it is probably not a good idea to return an `impl Trait` in a public function (that can be used from other crates), the reason being that there is no good way to put that `impl Trait` return value in a struct. 

That is, unless that Trait is Fn/FnMut/FnOnce, because then there is no better option. 

How about a lint warning against doing that?

**Comment by Manishearth** [comment]
Actually this is very much an intended use case for impl trait. It's not just for working around the existence of unnamable types, it's also for having flexibility in your APIs.
