### ISSUE TITLE
Lint Suggestion: cast of function to numbers

### ISSUE THREAD

**Issue by skade** [rust-lang-nursery/rust-clippy#2776]
This code compiles:

```rust
fn rand() -> i32 {
    4 // chosen by fair dice roll
}

fn test() -> i64 {
    12 * (rand as i64) // oops, forgot the calling brackets
}

fn main() {
    println!("{}", test());
}
```

It probably doesn't do anything the user intended, though, it returns 12 * `memory address of rand`, as it casts the `rand` function pointer to i64.

I suggest adding a lint for an numeric casts of fn pointer fixed size numbers, along with a text similar to "casting of fn()-pointer to a fixed size int, did you mean to call it instead?".

Report: https://www.reddit.com/r/rust/comments/8ke7sz/rust_2018_an_epochal_release/dz7v3cr/

**Comment by oli-obk** [comment]
duplicate of https://github.com/rust-lang-nursery/rust-clippy/issues/2588
