### ISSUE TITLE
lint against impl trait in the argument position

### ISSUE THREAD

**Issue by warlord500** [rust-lang-nursery/rust-clippy#2789]
while rust has just introduced impl trait to stable, impl trait in the argument position should be an official discouraged practice because there are now three ways to write a generic function. 

by linting against this we can encourage the older syntax more often

**Comment by Manishearth** [comment]
I don't think it currently is an officially discouraged practice especially since the RFC landed pretty recently.

**Comment by warlord500** [comment]
It currently isnt a discouraged practice just that one of the three ways to write generic function. With that, i think impl trait in args should be discouraged.

**Comment by oli-obk** [comment]
> just because it isnt officially discouraged yet.

https://github.com/rust-lang/rfcs/pull/2444#issuecomment-390719558 seems to suggest that that will never happen.

While we do have some unusual restriction lints, this is a special situation as there's loads of emotional stuff going on. I do not want to drag clippy into that discussion by offering a lint that goes against the majority of the community and against the official process for making changes.

**Comment by Manishearth** [comment]
Agreed.  Clippy does have restriction lints but those are not for "I dislike this", those are for specialized situations where you want additional restrictions.

And yeah, as an emotional subject we're probably not going to touch it anyway.

Clippy isn't an escape hatch around community process.

**Comment by Manishearth** [comment]
Yes, clippy _can_ accept such a lint, that doesn't mean it should.

A separate project for this sounds great.

**Comment by warlord500** [comment]
for your comment @oli-obk, clippy has definitely did accept a lint that falls under "I dislike this". 
and those lints are [shadow_reuse, shadow_same, shadow_](https://github.com/rust-lang-nursery/rust-clippy/blob/master/clippy_lints/src/shadow.rs) as well as [else if without else. ](https://github.com/rust-lang-nursery/rust-clippy/blob/master/clippy_lints/src/else_if_without_else.rs)

**Comment by oli-obk** [comment]
The shadow lints and the "else if without else" actually catch bugs in projects that have high safety requirements.

The only lint that comes to mind that violates this rule is the [assign_ops](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#assign_ops) lint, and I'll happily accept a PR that removes this lint!

**Comment by warlord500** [comment]
I have to disagree with @oli-obk, if you actually bother to read the why for those clipply lints, they all mention, "community members" believe having those features makes readability worse.
readability is inherently subjective. 

on, a finer note, being against the official process, isn't necessarily bad thing, It can be a good thing to show, how possibly broken an official process is. (I don't believe it is quite yet). my hope is that lint inclusion wasn't as bureaucratic as RFC process. however it is looking like it is. 
thank you for reading all of my comments, I appreciate any thought you have put into it.

**Comment by oli-obk** [comment]
> bother to read the why

uhm... [I literally read and categorized every lint description two months ago](https://github.com/rust-lang-nursery/rust-clippy/pull/2579/files)

The `else if without else` lint has an actual safety standard notice:

> Some coding guidelines require this (e.g. MISRA-C:2004 Rule 14.10).

The shadow* lints say

* Still, some may opt to avoid it in their code base
* Still, some argue that name shadowing like this hurts readability, because a value may be bound to different things depending on position in the code.
* Name shadowing can hurt readability, especially in large code bases, because it is easy to lose track of the active binding at any place in the code

If you prefer to have citations of coding guidelines or safety standards here, please open an issue or better yet a PR.

Our lints and their descriptions depend on community members maintaining them, this is not our dayjob.

**Comment by Manishearth** [comment]
The "why" in the codebase need not be the full set of reasons why. We're not great about documentation.

Shadowing actually _is_ problematic, but not too problematic. Those in safety-critical environments may like it.
