### ISSUE TITLE
Difficult to pin clippy, rustc versions due to naming conventions

### ISSUE THREAD

**Issue by mcandre** [rust-lang-nursery/rust-clippy#2792]
While waiting for intermittent clippy bugs to be fixed, I would like to roll back to a known working version of clippy and an associated version of rust. However, the naming conventions for nightly, beta, and stable prevent this from happening:

rust 1.27.0-nighty is no longer available for download via rustup under any kind of long term, reusable name. `rustup update 1.27.0-nightly`, `rustup update 1.27.0-beta`, and `rustup update 1.27.0` all fail. The only way to install 1.27.0 is by using its new name, "beta": `rustup update beta`.

In addition to this breaking in the future when 1.28.0 becomes the new "beta", this name doesn't even work right now for the task of getting a functioning clippy package installed. clippy 0.0.201 depends specifically on "1.27.0-nightly", rather than "1.27.0", so there appears to be no way of installing clippy 0.0.201 without corrupting the local rustup database to trick it into thinking that "1.27.0" is still a "nightly" release.

Sad panda.

**Comment by Manishearth** [comment]
There never was such a thing as 1.27-nightly, every nightly in that cycle gets the name.

What you want to do is find the date that nightly branched off and install nightly-date.

Versions work for stable and beta only. Nighties can only be identified by date.

**Comment by mcandre** [comment]
Update: I managed to find a name for the old 1.27.0-nightly that does work for getting it installed retroactively:

```console
$ rustup update nightly-2018-05-16
$ rustup default nightly-2018-05-16
```

It stinks that rustup has such awkward naming for these things, but at least this date method seems to work.

**Comment by mcandre** [comment]
@Manishearth In fact, `rustup update nightly-2018-05-16 && rustup default nightly-2018-05-16` turns out to install/active the wrong date of rust :(

clippy v0.0.201 wants 2018-05-16, but somehow "2018-05-15" is active:

```console
$ rustup show
Default host: x86_64-unknown-linux-gnu

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2018-05-16-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-2018-05-16-x86_64-unknown-linux-gnu (default)
rustc 1.27.0-nightly (f0fdaba04 2018-05-15)

$ rustc --version
rustc 1.27.0-nightly (f0fdaba04 2018-05-15)
```

**Comment by Manishearth** [comment]
The rustup date is the publish date, which may not be the rustc -V date
(that's when the binary is built)
