### ISSUE TITLE
Possibly suboptimal suggestion in `needless_range_loop`

### ISSUE THREAD

**Issue by qm3ster** [rust-lang-nursery/rust-clippy#2828]
```
  --> src/main.rs:32:18
   |
32 |         for x in origin.x..origin.x + width {
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
help: consider using an iterator
   |
32 |         for <item> in row.iter_mut().take(origin.x + width).skip(origin.x) {
   |             ^^^^^^    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I understand it just took the expressions of the ends of the range and put them inside the calls, but perhaps it's possible to understand what's going on here and suggest the following instead?
```rust
for cell in row.iter_mut().skip(origin.x).take(width) {}
```

**Comment by oli-obk** [comment]
To any implementor:

clippy has an expression comparator, you can use that one for figuring out whether in `x..y + z` the `x` and `y` are the same (`==` won't work because their spans and ids differ).

**Comment by qm3ster** [comment]
Some madman might also write a `x..y + z` where `x` and **`z`** are the same instead.

Maybe clippy should instead concoct an expression `(y + z) - x` and run that through expression simplification, and bail if the result still refers to `x`?

**Comment by oli-obk** [comment]
> Maybe clippy should instead concoct an expression (y + z) - x and run that through expression simplification, and bail if the result still refers to x / contains more nodes?

`*cough*` what expression simplification?

> Some madman might also write a x..y + z where x and z are the same instead.

Oh that... yea, let's just lint that, too, seems easy to just try both `x == y` and `x == z`. Brute force hackery all the way!
