### ISSUE TITLE
internal lint: forbid HashMap and HashSet and suggest the FxHash* variants

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#2853]
They are much more performant and we don't need any collision prevention in clippy.

Once it works nicely we can upstream it to rustc, because they totally need that, too

**Comment by dwijnand** [comment]
I might have a crack at this. Is there any prior art I can emulate for this? Are there any more mentoring instructions you could add to this, please? The more the merrier as I'm a Rust novice, and this is my first venture into the world of Clippy.

**Comment by oli-obk** [comment]
The simplest solution (not quite correct, but I don't think we care) is to basically create a lint that only implements `check_ident` and if the argument is equal to `HashMap` or `HashSet`, we lint and suggest to use `FxHashMap` and `FxHashSet`.

Doing this by name obviously is not right, but anyone naming their things `HashMap` or `HashSet` should be angrily stared at anyway.

This lint is only for inside clippy and rustc, so the false positives aren't problematic

**Comment by oli-obk** [comment]
Basically [this lint](https://github.com/oli-obk/rustfest2018_workshop/blob/master/src/main.rs#L62-L87) but with other names ;)

**Comment by mati865** [comment]
It may become relic of the past when https://github.com/rust-lang/rust/pull/56241 gets merged.
