### ISSUE TITLE
rustup component?

### ISSUE THREAD

**Issue by flyingP0tat0** [rust-lang-nursery/rust-clippy#2878]
Are there any plans to add `clippy` as a rustup component, in the same way `rustfmt` did? It would be pretty helpful to be able to just do a `rustup component add clippy`, instead of having to install `clippy` from source. Especially in CI this is quite frustrating, my linting stage takes way too long, just because it has to compile `clippy`.

**Comment by mati865** [comment]
It's planned but currently blocked on few things, like https://github.com/rust-lang/rust/pull/51122

**Comment by Manishearth** [comment]
https://manishearth.github.io/blog/2018/06/05/the-future-of-clippy-the-rust-linter/

Yes, but we're not there yet.

**Comment by flyingP0tat0** [comment]
Thanks for the explanation!
