### ISSUE TITLE
write_literal documentation unhelpful

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rust-clippy#2891]
This code ([playground](https://play.rust-lang.org/?gist=2cf999d1dc2ba6bf03535ea21b18b5c6&version=stable&mode=debug&edition=2015)):

```rust
macro_rules! impl_fmt_debug {
    ($id:ident) => {
        impl std::fmt::Debug for $id {
            fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "|{}|", stringify!($id))
            }
        }
    }
}
struct Foo();
impl_fmt_debug!(Foo);
fn main() {}
```

produces this lint:

```
warning: writing a literal with an empty format string
  --> src/main.rs:5:35
   |
5  |                 write!(f, "|{}|", stringify!($id))
   |                                   ^^^^^^^^^^^^^^^
...
13 | impl_fmt_debug!(Foo);
   | --------------------- in this macro invocation
   |
   = note: #[warn(write_literal)] on by default
   = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.211/index.html#write_literal
```

The lint documentation is pretty unhelpful about how to fix this, that is, how can I interpolate the result of `stringify!($id)` into the format string for this particular case within a macro?

**Comment by gnzlbg** [comment]
cc @oli-obk @Manishearth this might be a bug

**Comment by flip1995** [comment]
This is documented in the Known Problems section of the lint. Nevertheless it is indeed a bug, which would be nice if it could be fixed!

**Comment by oli-obk** [comment]
well.... you could do `concat!("|", stringify!($id), "|")`. But yea, we should not produce this lint for string literals produced by macros

**Comment by mcarton** [comment]
The playground code does not trigger this lint any more. (Probably related to ff0e5f967fde38242a1f2bf852082d2e105fc29c).
