### ISSUE TITLE
https://rust-lang-nursery.github.io/rust-clippy/v0.0.212 missing

### ISSUE THREAD

**Issue by marhel** [rust-lang-nursery/rust-clippy#2909]
The http help links output in the console by clippy v0.0.212 when doing `cargo clippy` such as https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#cast_lossless leads nowhere.

Navigating to https://rust-lang-nursery.github.io/rust-clippy/ shows links for current, master, and versions up to and including v0.0.211, but not one for v0.0.212.

This is after a rustup to `rustc 1.29.0-nightly (960f6046c 2018-07-08)`) earlier today.

**Comment by phansch** [comment]
Looks like we are missing the v0.0.212 git tag. Travis only pushes new docs for versions if there's a CI build for a git tag running. I can push the tag in a couple of hours and the docs should be there shortly after :+1:

**Comment by phansch** [comment]
The 0.0.212 are working now, so I'm going ahead and close this. Thanks for the report!
