### ISSUE TITLE
Clippy completely borked on latest nightly

### ISSUE THREAD

**Issue by bemeurer** [rust-lang-nursery/rust-clippy#2931]
On the latest nightly, `2018-07-16` clippy fails to build for me with 1184 errors. Since the build log/error log has about 7000 lines, I've uploaded it instead [`build.log`](https://github.com/rust-lang-nursery/rust-clippy/files/2203743/build.log).

From my quick look, it seems like a lot of the error are related to name changes in the HIR?

**Comment by Manishearth** [comment]
Try `rustup self update && rustup component add --toolchain=nightly clippy-preview`

**Comment by bemeurer** [comment]
@Manishearth Using `clippy-preview` solved it for me!
