### ISSUE TITLE
Why isn't indexing_slicing a restriction ?

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rust-clippy#2933]
It enforces a coding style that does not make sense for every crate, and it should IMO be opt-in, even with `-D clippy-pedantic`.

**Comment by mikerite** [comment]
To me this lint is similar to [integer_arithmetic](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#integer_arithmetic). Both of these lints suggest that you forgo basic features of the language (i.e. indexing and arithmetic operators) in the name of safety. `integer_arithmetic` is in restriction.

**Comment by Manishearth** [comment]
That seems like that was to be in accordance with the issue, but this definitely looks like a restriction lint and [is under restriction in the clippy rfc](https://github.com/rust-lang/rfcs/pull/2476/files). I'm in favor of switching back

@oli-obk thoughts?

**Comment by oli-obk** [comment]
Yea... I guess I was confused. Restriction makes more sense
