### ISSUE TITLE
Rerun even if build is done

### ISSUE THREAD

**Issue by Manishearth** [rust-lang-nursery/rust-clippy#2957]
If you run clippy after a build, it just says "Finished dev [unoptimized + debuginfo] target(s) in Xs", because it doesn't recompile.

We should do something to make clippy recompile (perhaps not replacing the compiled artifacts so it has minimal impact)

cc @alexcrichton ideally this would be a flag on `cargo check`.

**Comment by flip1995** [comment]
That issue is around for quite some time #2604

**Comment by Manishearth** [comment]
heh I tried to look for it and couldn't. I knew I'd seen this before
