### ISSUE TITLE
Lint impls within blocks not accompanied by the type definition.

### ISSUE THREAD

**Issue by Manishearth** [rust-lang-nursery/rust-clippy#2989]
https://twitter.com/iximeow/status/1024681349288845318

Rust supports putting `impl`s pretty much _anywhere_ .

Putting both impls and structs inside a scope is pretty common, but it's less common to put _just_ an impl inside a scope; it may mislead you into thinking the impl itself is scoped.

We should lint on cases where there's an impl within a block, where that impl is not accompanied by the corresponding struct.

Implementation wise the most efficient way to do this is likely to keep track of blocks and find impls within blocks, and then search the block contents for a type definition.

**Comment by Havvy** [comment]
This is #2124
