### ISSUE TITLE
Do not lint write_with_newline when there is more than one newline

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2990]
My code uses:

```rust
write!(file, "// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT\n\n")?;
```

I believe the above is clearer than Clippy's suggestion, in which one newline is written by the macro and one newline is written by my string:

```rust
writeln!(file, "// THIS FILE IS AUTOMATICALLY GENERATED; DO NOT EDIT\n")?;
```

Mentioning @estk who worked on this lint in #2630.

**Comment by estk** [comment]
This makes sense to me, @oli-obk?

**Comment by mikerite** [comment]
#2295 is similar.

**Comment by oli-obk** [comment]
@estk yea, let's not lint on multiple trailing newlines, only on a single one

**Comment by estk** [comment]
I think ill have time to knock this one out within a week.
