### ISSUE TITLE
bad get_unwrap suggestion

### ISSUE THREAD

**Issue by isonmad** [rust-lang-nursery/rust-clippy#3006]
```rust
let v = vec!["a","b"];
let _: Vec<_> = v.get(0..1).unwrap().to_vec();
//              ^^^^^^^^^^^^^^^^^^^^ help: try this: `&v[0..1]`

```
The suggestion changes the result to `&Vec` instead of `Vec`, so it doesn't compile. It has to be `v[0..1]` or `(&v[0..1])` instead.

**Comment by oli-obk** [comment]
We should

1. use the `Sugg` suggestion builder
2. optimize `Sugg` to produce `v[foo].bar()` instead of `(&v[foo]).bar()`

**Comment by ms2300** [comment]
Awesome thank you, I'll let you know if I have any questions

**Comment by ms2300** [comment]
Sorry for this ticket taking a bit longer than I thought, haven't had much time to concentrate. Besides the modified / new test, the fi should probably be in clippy_lints/src/utils/sugg.rs right?

**Comment by oli-obk** [comment]
"fi"?

You should only have to modify `sugg.rs` for the second part of this issue. The first one should just use the `Sugg` type.

**Comment by ms2300** [comment]
Cool, I'll have a fix soon. Thanks for the point in the right direction!

**Comment by ms2300** [comment]
I haven't made any progress on this ticket b/c I honestly don't fundamentally understand how to make the modification. I'm confused as to what part of the code actually recommends the fix for this problem and therefore don't even know where to begin :/

**Comment by oli-obk** [comment]
The suggestion is produced by the `format!` call in https://github.com/rust-lang-nursery/rust-clippy/blob/c81d70e6bdf264c62136b571760f152be9638ec0/clippy_lints/src/methods.rs#L1421

**Comment by CYBAI** [comment]
If #3178 is merged, maybe this can be closed?
