### ISSUE TITLE
Move `shadow_unrelated` to `pedantic`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#3012]
rationale from https://github.com/rust-lang/rfcs/pull/2476#discussion_r206257168

> It actually is a useful bug-catcher, and it's not quite idiomatic to have unrelated shadows, though marginally so.

**Comment by dwijnand** [comment]
This is slightly general/off-topic, but what's the material difference in being in the `pedantic` category over the `restriction` category? I guess I see them as very similar categories, so I wonder what I'm missing.

**Comment by Manishearth** [comment]
Pedantic checks are checks that have a benefit for all, however are annoying.

Restriction checks are ones which may not have the same level of benefit and are things that people may want to turn on on very specific areas of code for reasons.

We define the categories in https://github.com/rust-lang/rfcs/pull/2476

**Comment by dwijnand** [comment]
Ok, so the move is because it's considered more generally applicable (but potentially annoying). Gotcha! Thanks.
