### ISSUE TITLE
suggest iterator.count() instead of iterator.collect<Vec<_>>.len() 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#3034]
instead of doing something like
````rust
let len = iterator.collect<Vec<_>>.len();
````
we might want to suggest
````rust
let len = iterator.count();
````
however, ````.count()```` consumes the iterator so I am not sure if this is always applicable.

**Comment by shssoichiro** [comment]
I'll go ahead and pick this up.
