### ISSUE TITLE
False positive: similar_names gets confused by macro param names

### ISSUE THREAD

**Issue by illicitonion** [rust-lang-nursery/rust-clippy#3050]
Here's a minimal playground link: https://play.rust-lang.org/?gist=a1333019fbad19ebeb92f00abd6a0e64&version=nightly&mode=debug&edition=2015

The variable needs to specifically called `args` (`arg` is fine),

Possibly a duplicate of https://github.com/rust-lang-nursery/rust-clippy/issues/2651 and/or https://github.com/rust-lang-nursery/rust-clippy/issues/2927

**Comment by flip1995** [comment]
Yep dup of #2927. Thanks for reminding!

**Comment by mikerite** [comment]
Thanks for the minimal example.
