### ISSUE TITLE
Incomplete suggestion for op_ref

### ISSUE THREAD

**Issue by illicitonion** [rust-lang-nursery/rust-clippy#3051]
Playground link: https://play.rust-lang.org/?gist=b01329deb426e8ce84a2e54a7d26e158&version=nightly&mode=debug&edition=2015

The suggestion here is incomplete; if you just follow the suggestion verbatim and remove the `&` on the right hand side, you get a compile error because you're comparing a reference to a value (and rustc in fact tells you to precisely revert your "fix").

Instead, the suggestion should also suggest that you dereference the left hand side:
`if *v > 50`

**Comment by flip1995** [comment]
Dup of #2795
