### ISSUE TITLE
2018 edition vs feature gate lint

### ISSUE THREAD

**Issue by dcarosone** [rust-lang-nursery/rust-clippy#3088]
After a recent update, rustc/clippy gave me the following:

> :warning: the feature rust_2018_preview is included in the Rust 2018 edition

This is in code which, as per the migration guide at the time, has both
 * `edition = '2018'` in `Cargo.toml`, and 
 * `#![feature(rust_2018_preview)]` at the top of `main.rs`

The message is trying to tell me that the latter is redundant, but is a little unclear about what's wrong or what to do about it.  It could be improved:
* adding the word "redundant" somewhere in the warning, or perhaps replace "included" with "redundant".
* suggest an edit to remove the line.

**Comment by mati865** [comment]
This warning comes from `rustc` so Clippy has nothing to do with it.

**Comment by flip1995** [comment]
Yes, this is a rustc lint, not a Clippy lint.
