### ISSUE TITLE
unsafe within fn (not at fn scope) triggers error

### ISSUE THREAD

**Issue by crusty-dave** [rust-lang-nursery/rust-clippy#3134]
I am wondering why clippy considers not putting unsafe on the function an error?

Note that the stable compiler accepts the following without error:

```
    #[no_mangle]
    pub extern "C" fn context_free(jc_ptr: *mut Context) {
        //  Let it go out-of-scope to allow it to be deleted
        let  _jc = unsafe { Box::from_raw(jc_ptr) };
        let old_count = BATCH_CONTEXT_COUNT.fetch_sub(1, Ordering::SeqCst);
        println!("batch contexts {}", old_count - 1);
    }

```

error: this public function dereferences a raw pointer but is not marked `unsafe`
   --> jims_uri\src\lib.rs:619:41
    |
619 |         let  jc = unsafe {Box::from_raw(jc_ptr)};
    |                                         ^^^^^^
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#clippy::not_unsafe_ptr_arg_deref

Changing as follows prevents the error:

```
    #[no_mangle]
    pub unsafe extern "C" fn context_free(jc_ptr: *mut Context) {
        //  Let it go out-of-scope to allow it to be deleted
        let  _jc = Box::from_raw(jc_ptr);
        let old_count = BATCH_CONTEXT_COUNT.fetch_sub(1, Ordering::SeqCst);
        println!("batch contexts {}", old_count - 1);
    }

```

**Comment by Manishearth** [comment]
Of course the stable compiler accepts it, clippy contains _additional_ lints.

This code is unsound because you can call it from rust code with `context_free(12345 as *mut _)` and that will happily dereference any memory you want it to.

It is never okay for a safe function to accept a raw pointer that it then dereferences.

**Comment by crusty-dave** [comment]
I thought that the compiler knows that a function is unsafe implicitly by the inclusion of an unsafe statement within the function.  I don't see why lint needs to have a stronger enforcement than the compiler?  If you use the unsafe statement, you know that all safety assurances are gone.

**Comment by crusty-dave** [comment]
To state it another way, it seems that it is a bug in lint that it doesn't seem to recognize the unsafe construct unless it is applied at the function level.

**Comment by oli-obk** [comment]
The lint correctly understands what's going on. It is complaining about the fact that you can call `context_free(42 as *const _)` from safe code. Or even call `context_free(std::ptr::null())`. The only way to ensure that cannot be called from safe code is to make the function itself unsafe.
