### ISSUE TITLE
clippy 0.0.212 panics with assertion failure

### ISSUE THREAD

**Issue by darakshan** [rust-lang-nursery/rust-clippy#3153]
The following tiny program causes clippy 0.0.212 to panic with the message
thread 'main' panicked at 'assertion failed: parser.eat(&token::Eof)', tools/clippy/clippy_lints/src/write.rs:268:13

pub fn main() {
    println!("{}", a b);
}

**Comment by mati865** [comment]
Probably the same as https://github.com/rust-lang-nursery/rust-clippy/issues/3145

**Comment by mikerite** [comment]
Yes, it's a duplicate.
