### ISSUE TITLE
[Solved]: rustup component add clippy-preview does not add cargo subcommand

### ISSUE THREAD

**Issue by wezm** [rust-lang-nursery/rust-clippy#3179]
**Update** I solved this as I was writing the issue. I'm posting for future reference. 

The issue was that my `rustup` was too old. The fix:

```
rustup self update
```

After updating `rustup` I uninstalled, then reinstalled clippy and the cargo sub-command showed up as expected.

Before update: `rustup --version`: rustup 1.10.0 (c6a8f7c60 2018-01-25)
After update: `rustup --version`: rustup 1.13.0 (ea9259c1b 2018-07-16)

----

**OS:** macOS 10.13.6

I installed `clippy-preview` with `rustup` but running `cargo clippy` results in this error:

    error: no such subcommand: `clippy`

```
$ rustup component list

cargo-x86_64-apple-darwin (default)
rust-docs-x86_64-apple-darwin (default)
rust-std-x86_64-apple-darwin (default)
rustc-x86_64-apple-darwin (default)

$ rustup show

Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
1.16.0-x86_64-apple-darwin

active toolchain
----------------

stable-x86_64-apple-darwin (default)
rustc 1.29.0 (aa3ca1994 2018-09-11)
```

Looking in `~/.cargo/bin` there is no `cargo-clippy`, which I would expect. I've tried uninstalling and reinstalling to no avail.

```
$ ls ~/.cargo/bin
bindgen  cargo-fmt  dash2html  dot       pulldown-cmark  rq        rust-lldb  rustdoc  rustup        svd2rust  xargo
cargo    cobalt     diesel     pollybin  rls             rust-gdb  rustc      rustfmt  rustup-setup  tokei
```

No errors are reported when installing clippy:

```
$ rustup component add clippy-preview
info: downloading component 'clippy-preview'
info: installing component 'clippy-preview'
```

**Comment by mati865** [comment]
It's already said to update rustup first: https://github.com/rust-lang-nursery/rust-clippy#step-1-install-rustup
There is no point to keep this issue open.

**Comment by wezm** [comment]
I followed the instructions in the 1.29.0 blog post, which I image many people will be doing today, it does not mention updating rustup:

https://blog.rust-lang.org/2018/09/13/Rust-1.29.html#cargo-clippy

**Comment by flip1995** [comment]
Thanks for posting your solution!

**Comment by mati865** [comment]
Ah, so somebody haven't considered this case. Can we somehow ping them to edit that post to include `rustup update`?

cc @steveklabnik as the op on Reddit
