### ISSUE TITLE
type_complexity should not fire on FFI

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang-nursery/rust-clippy#3222]
Quoting @GabrielMajeri's magnificent comment on the use of `#[allow(clippy::type_complexity)]` to silence clippy's complaints about UEFI's overly complex entry points:

```
// Clippy correctly complains that this is too complicated, but we can't change the spec.
```

`cargo clippy -V` says...

```
clippy 0.0.212 (125907a 2018-09-17)
```

**Comment by flip1995** [comment]
[Context](https://github.com/GabrielMajeri/uefi-rs/blob/1129332f44a4002b7eee0779112ea124984ec1b4/src/proto/console/gop.rs#L39)

**Comment by joelgallant** [comment]
Looking to take a stab at this.
