### ISSUE TITLE
Out of date/incorrect instructions on crates.io

### ISSUE THREAD

**Issue by hauntsaninja** [rust-lang-nursery/rust-clippy#3246]
Hello,

I'm new to Rust! Someone mentioned I should install clippy, and I ended up at https://crates.io/crates/clippy, where the instructions didn't work. It appears clippy has been more integrated with cargo, and the instructions at this repo work perfectly. But I'm probably not the only person who'll visit that page and stumble, perhaps we could update it? Hopefully this is the right place to file this issue :)

Thanks!

**Comment by Manishearth** [comment]
We need to publish a version of clippy that swaps out the docs and also makes you use the other method of installing. I'll do this.

**Comment by Manishearth** [comment]
https://github.com/rust-lang-nursery/rust-clippy/pull/3247

**Comment by hauntsaninja** [comment]
Awesome, thank you!
