### ISSUE TITLE
Travis passes, despite build fail

### ISSUE THREAD

**Issue by flip1995** [rust-lang-nursery/rust-clippy#3260]
Despite clippy_lints fails to compile, travis passes and exits with `code 0`:

https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/437030960#L899

**Comment by matthiaskrgr** [comment]
Hummm I wonder if this is due to the `sleep` commands that I added...

**Comment by mati865** [comment]
@matthiaskrgr very likely the scripts return non 0 but it's not passed anywhere.
Something like that should work:
```
./ci/base-tests.sh && sleep 5
``

**Comment by flip1995** [comment]
> Hummm I wonder if this is due to the sleep commands that I added...

That might be it. @mati865 suggestion could solve this, let's try it!

**Comment by matthiaskrgr** [comment]
I'm already on it, waiting for my travis builds to fail.. :)
