### ISSUE TITLE
README.md lists lint categories but not which are on by default

### ISSUE THREAD

**Issue by 8573** [rust-lang-nursery/rust-clippy#3293]
`README.md` lists Clippy's lint categories, but, as far as I see, doesn't mention which categories are enabled by default — I assume `correctness` is and `pedantic` and `nursery` aren't, but I don't know about the others.

**Comment by oli-obk** [comment]
By default, `style`, `correctness`, `complexity` and `perf` are enabled

**Comment by sigustin** [comment]
I'd like to take this one please.

**Comment by sigustin** [comment]
Could someone check that I understood the issue correctly, please?
