### ISSUE TITLE
relicensing broke rust x.py dist

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang-nursery/rust-clippy#3311]
I tried updating the submodulei in https://github.com/rust-lang/rust/pull/54916 but `./x.py dist` fails with up to date clippy submodule

````
Building stage2 tool cargo-clippy (x86_64-pc-windows-msvc)
    Finished release [optimized] target(s) in 0.74s
[TIMING] ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-pc-windows-msvc" }, target: "x86_64-pc-windows-msvc", tool: "cargo-clippy", path: "src/tools/clippy", mode: ToolRustc, is_optional_tool: true, source_type: Submodule, extra_features: [] } -- 0.893
thread 'main' panicked at 'fs::File::open(&src) failed with The system cannot find the file specified. (os error 2)', bootstrap\lib.rs:1291:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: C:\projects\rust\build\bootstrap\debug\bootstrap dist
Build completed unsuccessfully in 1:13:05
Command exited with code 1
set PATH=%PATH%;"C:\Program Files (x86)\Windows Kits\10\Debuggers\X64"
if exist %LOCALAPPDATA%\CrashDumps for %%f in (%LOCALAPPDATA%\CrashDumps\*) do cdb -c "k;q" -G -z "%%f"
````
I bisected this to https://github.com/rust-lang-nursery/rust-clippy/commit/ca437e81a730e2b449b50e00f3bb7f3d381f327d

**Comment by matthiaskrgr** [comment]
Note: readding an empty `LICENSE` file fixes the dist build.

**Comment by oli-obk** [comment]
Ah, we need to fix this on the rustc side. There's some code in `src/bootstrap/dist.rs` that explicitly copies `LICENSE` for clippy.

**Comment by matthiaskrgr** [comment]
Ok, I tweaked the `run()` function to point to the new files, now waiting for the build to finish :)

**Comment by matthiaskrgr** [comment]
Updated the pr via https://github.com/rust-lang/rust/pull/54916/commits/9c651b3b317575cd9241e8bee343116c9fb81bc7 
I'll close this.
