### ISSUE TITLE
Color cannot be turned off

### ISSUE THREAD

**Issue by starblue** [rust-lang-nursery/rust-clippy#3328]
clippy 0.0.212 (9d33731 2018-10-11)

Neither setting `TERM=none` nor `--color never` turn off color in the output.
Yellow on a light background is completely unreadable, and light green is not much better, so as is it is unusable for me.

**Comment by starblue** [comment]
Putting `--color=never` after every cargo subcommand is not a solution, because it can't easily be done for all subcommands. Obviously I don't want to type it every time, so I have a wrapper script:
<pre>
#!/bin/sh
TERM=none exec "${HOME}"/.cargo/bin/cargo --color never "$@" 
</pre>
What is missing is a global way to turn off color, and the closest thing I found is `TERM=none`, which unfortunately doesn't work here. Using a dedicated global environment variable setting would be even better (preferably `CLICOLOR=0`).

**Comment by oli-obk** [comment]
How do you do it when using `cargo build`? Does `TERM=none` work there?

**Comment by starblue** [comment]
No, a quick test showed that `TERM=none` has no effect.
It is the `--color none` in `cargo `--color none build` that works,

**Comment by starblue** [comment]
I found a solution:
<pre>
[term]
color = 'never'
</pre>
in `~/.cargo/config` seems to do the job.

**Comment by oli-obk** [comment]
Great!
