### ISSUE TITLE
Nightly build failures

### ISSUE THREAD

**Issue by phansch** [rust-lang-nursery/rust-clippy#3367]
The build is currently failing on nightly due to:

* [x] A broken compiletest-rs (Fix: https://github.com/laumann/compiletest-rs/pull/130) - need to wait for new release or use master
* [x] A rustc bug: https://github.com/rust-lang/rust/issues/55376

**Comment by matthiaskrgr** [comment]
the `lint-without-lint-pass` lint fires in a weird way suddenly
https://travis-ci.org/rust-lang-nursery/rust-clippy/jobs/447631961#L1161

**Comment by matthiaskrgr** [comment]
Ok it didn't show up on a PR I just made ... maybe it's spurious?

**Comment by oli-obk** [comment]
> maybe it's spurious?

That's scary!

Maybe travis is prepping for halloween?

On a more serious note. That's really scary. Not sure how that can happen

**Comment by matthiaskrgr** [comment]
I just checked again and it was only a single PR (never master) where this fired, so probably my bad and false alarm...

**Comment by flip1995** [comment]
The link broke for some reason (I tested it locally with the latest nightly). I have no idea why it broke, but I have a fix for it, that I will push this evening.

**Comment by flip1995** [comment]
Pushed a fix to #3378

**Comment by Manishearth** [comment]
Master broke clippy, so I'm tempfixing the tempfix by installing an older nightly for the rustup-toolchain-install-master build 

https://github.com/rust-lang-nursery/rust-clippy/pull/3383

**Comment by matthiaskrgr** [comment]
The upstream rustc bug has been fixed and temporary ci fixes have been rolled back.
Closing :)
