### ISSUE TITLE
clippy doesn't appear to fully install in NetBSD

### ISSUE THREAD

**Issue by mcandre** [rust-lang-nursery/rust-clippy#3393]
The clippy-preview component is able to "install" clippy, but no binary is placed anywhere on the system.

```console
$ rustup component add clippy-preview
info: component 'clippy-preview' for target 'x86_64-unknown-netbsd' is up to date

$ clippy
clippy: not found

$ sudo find / -name 'clippy*' -print
/home/vagrant/.rustup/toolchains/stable-x86_64-unknown-netbsd/share/doc/clippy
/home/vagrant/.rustup/toolchains/stable-x86_64-unknown-netbsd/bin/clippy-driver
```

I'm using NetBSD 7.1.1, amd64.

**Comment by Manishearth** [comment]
`clippy` isn't how you invoke it, try `cargo-clippy`

Also, the binary already exists (`cargo-clippy`) as a rustup shim, but installing the component gets you the actual inner binary
