### ISSUE TITLE
lint `From<&str>` or `From<String>` implementations

### ISSUE THREAD

**Issue by llogiq** [rust-lang-nursery/rust-clippy#691]
suggest implementing `FromStr` instead

Why is this bad: Usually not all strings represent correct values, so using `FromStr` allows us to return a `Result` that includes error information.

**Comment by fhartwig** [comment]
I'm not convinced that the usefulness-to-annoyance ratio is high enough for this one. For example, I like to have newtype wrappers for things that are basically `String`s but have some more specific meaning in my program (think `UserName` etc.). I also like implementing `From<String>` for these types and there is no parsing needed, so there is no point in returning a `Result`.

**Comment by oli-obk** [comment]
> I also like implementing From<String> for these types and there is no parsing needed, so there is no point in returning a Result.

Are you sure that this is sensible? I got the impression that `From` and `Into` are for same semantics, but different representations. But you are changing the semantics while keeping the representation.

**Comment by llogiq** [comment]
@fhartwig Yeah, I hadn't thought of that. So we either look into the type and avoid linting if the type has a string field, or make the lint `allow` by default and live with the false positives.

**Comment by fhartwig** [comment]
@oli-obk I don't really see any issues with it. And to give an example from `std`, there is a `From<String>` instance for `Vec<u8>`, which I think is the same data structure with different semantics. But I may be misunderstanding your question. But anyway, my broader point is that not every conversion from a String can fail, so we should be careful about false positives.

@llogiq Not sure. I'm not generally a fan of 'clever' lints that are prone to false positives, false negatives or other edge cases. On the other hand, if this is a common enough problem, it might be worth it. I haven't really seen much abuse of `From<String>` myself, so you probably have more information to make that decision.

**Comment by llogiq** [comment]
@fhartwig Why not be more clever and less arbitrary at once: If we have a `From<&str>` or `From<String>` implementation whose `.from(_)` method contains a `panic!()` or `unwrap` (of Option/Result), we lint, otherwise, keep it as is.
